import {I_CartoonApi} from "../../models/server/films/interfaces";

export const allCartoonApi: I_CartoonApi[] = [
    {
        id: 0,
        nameEn: 'Kung Fu Panda 4',
        nameRu: 'Кунг-фу Панда 4',
        imgSm: 'kung-fu-panda-4-min.jpg',
        imgLg: 'kung-fu-panda-4-md.jpg',
        video: 'Кунг-фу Панда 4 _ Русский трейлер с МИХАИЛОМ ГАЛУСТЯНОМ в дубляже Red Head Sound.mp4',
        duration: 93,
        year: 2024,
        type: 'cartoon',
        director: 'Mike Mitchell',
        actors: ['Jack Black','Awkwafina','Viola Davis','Dustin Hoffman'],
        category: ['fantasy','adventure','comedy','family'],
        aboutEn: 'Panda named Po, a fearless Dragon Warrior who has defeated many powerful enemies on his way, must choose a successor to become the spiritual leader of the Valley of Peace himself. Suddenly, he is faced with a new enemy seeking to take over the Valley, which is many times stronger than all the previous ones — an evil witch who can take the form of any kung fu master. To come out of the fight victorious, Po has to join forces with the steppe fox Zhen, a young street thief who pretends to be a Dragon Warrior.',
        aboutRu: 'Панда по имени По, бесстрашный Воин Дракона, победивший на своем пути множество могущественных врагов, должен выбрать себе приемника, чтобы самому стать духовным предводителем Долины Мира. Неожиданно он сталкивается с новым врагом, стремящимся захватить Долину, который в разы сильнее всех предыдущих, — злой ведьмой, способной принимать форму любого мастера кунг-фу. Чтобы выйти из схватки победителем, По приходится объединить усилия со степной лисицей Чжэнь — молодой уличной воровкой, претендующей на роль Воина Дракона.',
        rating: 5,
    },
    {
        id: 1,
        nameEn: 'X-Men \'97',
        nameRu: 'Люди Икс \'97',
        imgSm: 'x-men97-min.jpg',
        imgLg: 'x-men97-md.jpg',
        video: 'Marvel Animation\'s X-Men \'97 _ Official Trailer _ Disney .mp4',
        duration: 30,
        year: 2024,
        type: 'cartoon',
        director: 'Stan Lee',
        actors: ['Cal Dodd','George Buza','Holly Chou','Ray Chase'],
        category: ['fantasy','adventure','action'],
        aboutEn: 'A few months after the death of Professor X, who created the X-Men, the wayward and responsible Cyclops became the leader of the mutants. Mutants continue to actively use their supernatural abilities to protect humanity from various threats, but people still hate and fear them. Despite numerous difficulties, clashes with organizations seeking to destroy mutants, and the unexpected return of Magneto, the X-Men are fighting numerous villains and performing the most difficult tasks to the limit of their capabilities.',
        aboutRu: 'Спустя несколько месяцев после смерти профессора Икс, который создал Людей Икс, лидером мутантов стал своенравный и ответственный Циклоп. Мутанты продолжают активно использовать свои сверхъестественные способности для защиты человечества от различных угроз, но люди по-прежнему ненавидят их и боятся. Несмотря на многочисленные трудности, столкновения с организациями, стремящимися уничтожить мутантов, и неожиданное возвращения Магнето, Люди Икс ведут борьбу с многочисленными злодеями и выполняют самые сложные задачи на пределе своих возможностей.',
        rating: 4.5
    },
    {
        id: 2,
        nameEn: 'Teenage Mutant Ninja Turtles: Mutant Mayhem',
        nameRu: 'Черепашки-ниндзя: Погром мутантов',
        imgSm: 'teenage-mutant-ninja-turtules-min.jpg',
        imgLg: 'teenage-mutant-ninja-turtules-md.jpg',
        video: 'Черепашки-ниндзя_ Погром мутантов — Официальный дублированный трейлер  (1).mp4',
        duration: 99,
        year: 2023,
        type: 'cartoon',
        director: 'Jeff Rowe',
        actors: ['Micah Abbey','Shamon Brown Jr.','Nicolas Cantu','Brady Noon'],
        category: ['fantasy','adventure','action','comedy','family'],
        aboutEn: '15 years ago, Stockman\'s experiments led to the release of a mutagen into the urban sewers of New York, where later the martial arts master Splinter became an adoptive father to four mutant turtles. Now the turtle brothers have matured, gained experience in martial arts and strive to get out of the sewers to become part of the upper world and interact with people on equal terms. One day, the turtles meet an ambitious journalism student, April O\'Neill, and decide to become crime fighters on the streets of the metropolis, whose existence is threatened by the insidious plans of Superfly, the creepy creation of Stockman and the leader of a gang of mutants.',
        aboutRu: '15 лет назад эксперименты Стокмана привели к попаданию мутагена в городскую канализацию Нью-Йорка, где впоследствии мастер боевых искусств Сплинтер стал приемным отцом для четырех черепашек-мутантов. Теперь братья-черепашки возмужали, обрели опыт в боевых искусствах и стремятся выбраться из канализации, чтобы стать частью верхнего мира и взаимодействовать с людьми на равных. Однажды черепашки знакомятся с амбициозной студенткой-журналистской Эйприл О’Нил и решают стать борцами с преступностью на улицах мегаполиса, чье существование оказывается под угрозой из-за коварных планов Суперфлая — жуткого создания Стокмана и лидера банды мутантов.',
        rating: 4.5
    },
    {
        id: 3,
        nameEn: 'Nimona',
        nameRu: 'Нимона',
        imgSm: 'nimona-min.jpg',
        imgLg: 'nimona-md.jpg',
        video: 'Нимона - русский трейлер (субтитры) _ мультфильм 2023 _ Netflix.mp4',
        duration: 103,
        year: 2023,
        type: 'cartoon',
        director: 'Nick Bruno',
        actors: ['Chloë Grace Moretz','Riz Ahmed','Eugene Lee Yang','Frances Conroy'],
        category: ['fantasy','adventure','action','comedy','family','thriller'],
        aboutEn: 'In the futuristic medieval world, the knight Ballester has become the main suspect in the murder of the queen, after which he is forced to flee. A cheeky teenage girl named Nim, she turns out to be the only one who is able to help a wanted fugitive clear his own name from suspicion. Soon, the knight unexpectedly discovers that his companion is a werewolf creature that Ballister has been trained to destroy. In a deadly situation, she becomes the perfect assistant to fight the countless servants of the kingdom who are hunting them.',
        aboutRu: 'В футуристическом средневековом мире рыцарь Баллистер стал главным подозреваемым в убийстве королевы, после чего он вынужден спасаться бегством. Дерзкая девочка-подросток по имени Нимона оказывается единственной, кто способен помочь разыскиваемому беглецу очистить собственное имя от подозрений. Вскоре рыцарь неожиданно обнаруживает, что его соратница является существом-оборотнем, которых Баллистер обучен уничтожать. В смертельно опасной ситуации Нимона становится идеальным помощником для борьбы с бесчисленными слугами королевства, ведущими на них охоту.',
        rating: 4
    },
    {
        id: 4,
        nameEn: 'Puss in Boots: The Last Wish',
        nameRu: 'Кот в сапогах 2: Последнее желание',
        imgSm: 'puss-in-boots-2-min.jpg',
        imgLg: 'puss-in-boots-2-md.jpg',
        video: 'КОТ В САПОГАХ_ ПОСЛЕДНЕЕ ЖЕЛАНИЕ I Трейлер 1 I Скоро в кино.mp4',
        duration: 102,
        year: 2022,
        type: 'cartoon',
        director: 'Joel Crafword',
        actors: ['Antonio Banderas','Salma Hayek','Harvey Guillén','Florence Pugh'],
        category: ['fantasy','adventure','action','comedy','family'],
        aboutEn: 'The knight of the tail and Sword, aka Puss in Boots, heroically defeats the formidable giant, but at the same time loses the eighth of his nine lives. The risk of dying completely and irrevocably prompts the main character to give up adventures and become the new pet cat of Mama Luna, where he makes friends with the therapy dog Perrault. The renewed confrontation with their sworn enemies — the criminal clan of Goldilocks and the three bears - does not allow them to meet a quiet and peaceful old age. With his last life in reserve, which becomes priceless, Puss in Boots turns to his long-time beloved Kitty Myagolapka for help.',
        aboutRu: 'Рыцарь хвоста и шпаги, он же Кот в сапогах, героически побеждает грозного великана, но вместе с тем лишается восьмой из девяти своих жизней. Риск умереть окончательно и безвозвратно побуждает главного героя завязать с авантюрами и стать новой домашней кошкой Мамы Луны, где тот заводит дружбу с собакой-терапевтом Перро. Встретить тихую и спокойную старость не дает возобновившееся противостояние со своими заклятыми врагами — преступным кланом Златовласки и трех медведей. Имея в запасе последнюю жизнь, которая становится бесценной, Кот в сапогах обращается за помощью к своей давней возлюбленной Кисе Мягколапке.',
        rating: 4.8
    },
    {
        id: 5,
        nameEn: 'The Super Mario Bros. Movie',
        nameRu: 'Братья Супер Марио в кино',
        imgSm: 'the-super-mario-bros-min.jpg',
        imgLg: 'the-super-mario-bros-md.jpg',
        video: 'The Super Mario Bros. Movie _ Official Trailer.mp4',
        duration: 92,
        year: 2023,
        type: 'cartoon',
        director: 'Aaron Horvath',
        actors: ['Chris Pratt','Anya Taylor-Joy','Charlie Day','Jack Black'],
        category: ['fantasy','adventure','comedy','family'],
        aboutEn: 'The purposeful and optimistic Mario has been inseparable from his younger brother, the timid and shy Luigi, whom he always protected from bullies. Both leave their former employer to open their own plumbing business in Brooklyn, spending all their savings on a commercial. One day Mario and Luigi go down to the underground utilities to fix the water supply, where they suddenly fall through a mysterious pipe into a fantastic Mushroom kingdom. There, the main characters are drawn into an incredible adventure to save Princess Peach from the evil Bowser.',
        aboutRu: 'Целеустремленный и оптимистичный Марио с детства неразлучен со своим младшим братом, робким и застенчивым Луиджи, которого всегда защищал от хулиганов. Оба уходят от своего прежнего работодателя, чтобы открыть собственный сантехнический бизнес в Бруклине, потратив все сбережения на рекламный ролик. Однажды Марио и Луиджи спускаются в подземные коммуникации, чтобы починить водопровод, где неожиданно попадают через таинственную трубу в фантастическое Грибное королевство. Там главные герои втягиваются в невероятные приключения по спасению принцессы Пич от злобного Боузера.',
        rating: 4.6,
    },
    {
        id: 6,
        nameEn: 'DC League of Super-Pets',
        nameRu: 'Суперпитомцы',
        imgSm: 'league-of-super-pets-min.jpg',
        imgLg: 'league-of-super-pets-md.jpg',
        video: 'DC Лига Суперпитомцы _ Трейлер _ В кино с 19 мая.mp4',
        duration: 106,
        year: 2022,
        type: 'cartoon',
        director: 'Jared Stern',
        actors: ['Dwayne Johnson','Kevin Hart','Kate McKinnon','John Krasinski'],
        category: ['fantasy','adventure','action','comedy','family','criminal'],
        aboutEn: 'Superpace Crypto, known for his supernatural agility and strength, is fighting rampant crime on the streets of Metropolis, actively helping Superman. When a team of Justice League superheroes, including Superman, is captured by Lex Luthor, Crypto must lead a group of pets endowed with superpowers to save his master and his colleagues. From the invincible dog Ace, who has powerful strength, to Merton the turtle, who is capable of high speed, Crypto leads eccentric pets embarking on the first joint mission to fight evil.',
        aboutRu: 'Суперпес Крипто, известный своей сверхъестественной ловкостью и силой, ведет борьбу с разгулом преступности на улицах Метрополиса, активно помогая Супермену. Когда команда супергероев Лига Справедливости, включая Супермена, захвачена Лексом Лютором, Крипто должен возглавить группу домашних питомцев, наделенных суперспособностями, чтобы спасти своего хозяина и его коллег. От непобедимого пса Эйса, обладающего могущественной силой, до черепахи Мертона, способной развивать высокую скорость, Крипто руководит эксцентричными домашними животными, приступающими к первой совместной миссии по борьбе со злом.',
        rating: 4.1,
    },
    {
        id: 7,
        nameEn: 'I Am Groot',
        nameRu: 'Я есть Грут',
        imgSm: 'i-am-groot-min.jpg',
        imgLg: 'i-am-groot-md.jpg',
        video: 'I Am Groot _ Official Trailer _ Disney+.mp4',
        duration: 4,
        year: 2022,
        type: 'cartoon',
        director: 'Kersten Lepore',
        actors: ['Vin Diesel','Fred Tatasciore','Bradley Cooper','Terri Douglas','James Gunn'],
        category: ['fantasy','adventure','action','comedy'],
        aboutEn: 'A series of animated short films about the adventures of funny and inquisitive kid Groot from Guardians of the Galaxy. In each episode, a tree—like character embarks on another adventure - from his first steps in a dangerous and unpredictable world to mind-blowing dances with an alien and encounters with various bizarre characters. Being an ambitious kid, Groot stubbornly moves towards achieving his goals, but his antics periodically cause large-scale troubles, including the unintended destruction of an alien community and a large-scale explosion.',
        aboutRu: 'Серия анимационных короткометражек о приключениях забавного и любознательного малыша Грута из «Стражей Галактики». В каждом эпизоде древовидный персонаж отправляется навстречу очередным приключениям — от его первых шагов в опасном и непредсказуемом мире до умопомрачительных танцев с инопланетянином и встречей с различными причудливыми персонажами. Будучи амбициозным малышом, Грут упорно движется к достижению своих целей, однако его выходки периодически вызывают масштабные неприятности, включая непреднамеренное уничтожение инопланетного сообщества и масштабный взрыв.',
        rating: 4.4
    },
    {
        id: 8,
        nameEn: 'Minions: The Rise of Gru',
        nameRu: 'Миньоны: Грювитация',
        imgSm: 'minions-the-rise-of-gru-min.jpg',
        imgLg: 'minions-the-rise-of-gru-md.jpg',
        video: 'МИНЬОНЫ_ ГРЮВИТАЦИЯ _ Трейлер 1 _ в кино с 2 июля.mp4',
        duration: 90,
        year: 2022,
        type: 'cartoon',
        director: 'Kyle Balda',
        actors: ['Steve Carell','Pierre Coffin','Alan Arkin','Taraji P. Henson'],
        category: ['fantasy','adventure','family','comedy','criminal'],
        aboutEn: 'In the 1970s, at the top of the villainous hierarchy is the "Evil Six" — a team of professional unscrupulous criminals who, after the overthrow of their leader, Grandfather Brass Knuckles, are looking for a new member. 11-year-old Gru, who dreams of becoming a supervillain, signs up for an interview, for which he got his own villainous lair and an army of obedient minions. Upset because of the ridicule in his address, he famously steals from the Evil Six their main pride — an ancient magic amulet, which brings upon himself a series of unpredictable misadventures.',
        aboutRu: 'В 1970-х годах на вершине злодейской иерархии находится «Злобная шестерка» — команда профессиональных беспринципных преступников, которая после свержения своего лидера Деда Кастета подыскивает себе нового участника. На собеседование записывается 11-летний Грю, мечтающий стать суперзлодеем, для чего обзавелся собственным злодейским логовом и армией послушных миньонов. Расстроенный из-за насмешек в свой адрес, он лихо крадет у Злобной шестерки их главную гордость — древний волшебный амулет, чем навлекает на себя череду непредсказуемых злоключений.',
        rating: 4.5
    },
    {
        id: 9,
        nameEn: 'Lightyear',
        nameRu: 'Базз Лайтер',
        imgSm: 'lightyear-min.jpg',
        imgLg: 'lightyear-md.jpg',
        video: 'Lightyear _ Official Trailer.mp4',
        duration: 105,
        year: 2022,
        type: 'cartoon',
        director: 'Angus MacLane',
        actors: ['Chris Evans','Keke Palmer','Peter Sohn','Taika Waititi'],
        category: ['fantasy','adventure','action','drama','family'],
        aboutEn: 'Disney and Pixar present the adventure story of the legendary space ranger Buzz Lightyear.',
        aboutRu: 'Disney и Pixar представляют историю приключений легендарного космического рейнджера Базза Лайтера.',
        rating: 4.1
    },
    {
        id: 10,
        nameEn: 'Hotel Transylvania: Transformania',
        nameRu: 'Монстры на каникулах: Трансформания',
        imgSm: 'hotel-transylvania-min.jpg',
        imgLg: 'hotel-transylvania-md.jpg',
        video: 'Монстры на каникулах 4_ Трансформания — Русский трейлер (2021).mp4',
        duration: 87,
        year: 2022,
        type: 'cartoon',
        director: 'Derek Drymon',
        actors: ['Andy Samberg','Selena Gomez','Kathryn Hahn','Jim Gaffigan'],
        category: ['fantasy','adventure','action','comedy','horror','family'],
        aboutEn: 'Dracula and his friends will plunge into another stream of adventures: this time Van Helsing\'s new invention turns a vampire and his friends into ordinary people, and Johnny becomes a real monster. Now Drak and his comrades will have to discover a new world in which they will not have supernatural abilities, and Johnny will have to reveal the unusual essence of a creepy monster. In addition, the main characters need to go from the Transylvania hotel on an exciting journey around the world in order to find a remedy that will return everything to its place.',
        aboutRu: 'Дракуле и его приятелям предстоит окунуться в очередной поток приключений: на этот раз новое изобретение Ван Хельсинга превращает вампира и его друзей в обычных людей, а Джонни становится настоящим чудовищем. Теперь Драку и его товарищам придётся открыть для себя новый мир, в котором у них не будет сверхъестественных способностей, а Джонни – раскрыть непривычную для себя сущность жутковатого монстра. К тому же, главным героям необходимо отправиться из отеля «Трансильвания» в захватывающий путь по всему свету, чтобы отыскать средство, которое вернёт всё на свои места.',
        rating: 4.9
    },
    {
        id: 11,
        nameEn: 'Team Hot Wheels: The Skills to Thrill',
        nameRu: 'Hot Wheels. За гранью воображения',
        imgSm: 'team-hot-wheels-the-skills-to-thrill-min.jpg',
        imgLg: 'team-hot-wheels-the-skills-to-thrill-md.jpg',
        video: 'Trailer 1 _ The Skills to Thrill _ @HotWheels.mp4',
        duration: 45,
        year: 2015,
        type: 'cartoon',
        director: 'Matt Danner',
        actors: ['Ben Diskin','Jessica Gee-George','Grant George','David Lodge'],
        category: ['adventure','action','comedy'],
        aboutEn: 'Gage, Wyatt, Brandon and Rhett are members of the Hot Wheels racing team who try to be good guys, but often do more harm than good for their hometown. One day they go to the laboratory of the mad scientist Larry, where they meet his twin brother Gary, who has arrived in the city with his new invention - an on—board remote control for cars. His invention allows people to drive cars without having to drive them, but very soon the "Hot Wheels" discover that with the help of his invention, Gary pursues insidious plans…',
        aboutRu: 'Гейдж, Вятт, Брэндон и Ретт — члены гоночной команды «Hot Wheels», которые стараются быть хорошими парнями, однако часто приносят больше вреда, чем пользы для своего родного города. Однажды они отправляются в лабораторию сумасшедшего ученого Ларри, где встречают его брата-близнеца Гэри, прибывшего в город со своим новым изобретением — бортовым пультом дистанционного управления для автомобилей. Его изобретение позволяет людям ездить на автомобилях без необходимости управлять ими, но очень скоро «Hot Wheels» обнаруживают, что с помощью своего изобретения Гэри преследует коварные планы…',
        rating: 4.9
    },
    {
        id: 12,
        nameEn: 'Heroes of Envell',
        nameRu: 'Герои Энвелла',
        imgSm: 'heroes-of-envel-min.jpg',
        imgLg: 'heroes-of-envel-md.jpg',
        video: 'Герои Энвелла - Трейлер нового российского фантастического мультфильма для детей и подростков..mp4',
        duration: 11,
        year: 2017,
        type: 'cartoon',
        director: 'Anton Lanshakov',
        actors: ['Olga Zubkova','Vladimir Antonik','Artem Koshman','Yola Sanko'],
        category: ['adventure','fantasy','comedy'],
        aboutEn: 'The plot centers on four school friends who, trying to find mobile phones seized in class, find a strange laptop. By turning it on, the guys get to a bizarre place, and after they are offered to choose a class and study, friends, being avid gamers, are surprised to realize that they are in a computer game. After defeating the training monsters, they complete a training mission and find themselves back at school, while retaining their gaming skills and abilities. And despite the great desire to return the laptop to where they found it, curiosity prevails, and our heroes repeatedly find a reason to be back in the game.',
        aboutRu: 'В центре сюжета оказываются четверо школьных друзей, которые, пытаясь отыскать изъятые на уроке мобильные телефоны, находят странный ноутбук. Включив его, ребята попадают в причудливое место, а после того, как им предлагают выбрать класс и пройти обучение, друзья, будучи заядлыми геймерами, с удивлением понимают, что оказались в компьютерной игре. Победив тренировочных монстров, они проходят обучающую миссию и вновь оказываются в школе, сохранив при это игровые навыки и способности. И несмотря на огромное желание вернуть ноутбук туда, где они его нашли, любопытство одерживает верх, и наши герои раз за разом находят причину, чтобы вновь оказаться в игре.',
        rating: 4.4
    },
    {
        id: 13,
        nameEn: 'Team Hot Wheels: Build the Epic Race',
        nameRu: 'Hot Wheels. Мегатрасса',
        imgSm: 'team-hot-wheels-build-the-epic-race-min.jpg',
        imgLg: 'team-hot-wheels-build-the-epic-race-md.jpg',
        video: 'Trailer .mp4',
        duration: 45,
        year: 2015,
        type: 'cartoon',
        director: 'Matt Danner',
        actors: ['Ben Diskin','Doug Erholtz','Jessica Gee-George','Grant George'],
        category: ['adventure','action','comedy'],
        aboutEn: 'The members of the Hot Wheels racing team are looking forward to the start of the epic Hot Wheels City race, which will take place on the local megatrass, hoping that they will be able to achieve victory in the prestigious competition. However, the Road Pirates team has other plans, as they intend to defeat their sworn opponents, even if it means acting insidiously, meanly and unconventionally. The first step from "Road Pirates" is to infiltrate "Hot Wheels" and then get Vyatt expelled. This is how a large-scale confrontation between two excellent racing teams begins.',
        aboutRu: 'Члены гоночной команды «Hot Wheels» с нетерпением ждут начала эпической гонки «Hot Wheels City», которая пройдет на местной мегатрассе, надеясь, что им удастся добиться победы в престижном соревновании. Однако у команды «Road Pirates» другие планы, поскольку они намерены победить своих заклятых противников, даже если для этого придется действовать коварно, подло и нестандартно. Первый шаг от «Road Pirates» состоит в том, чтобы проникнуть в «Hot Wheels», а затем добиться исключения Вятта. Так начинается масштабное противостояние двух отличных гоночных команд.',
        rating: 4.5
    },
    {
        id: 14,
        nameEn: 'Ejen Ali / Agent Ali',
        nameRu: 'Агент Али',
        imgSm: 'agent-ali-min.jpg',
        imgLg: 'agent-ali-md.jpg',
        video: 'EJEN ALI - KECEMASAN!.mp4',
        duration: 22,
        year: 2016,
        type: 'cartoon',
        director: 'Muhammad Usamah Zaid',
        actors: ['Shafiq Isa','Noorhayati Maslini','Ida Rahayu','Azman Zulkiply'],
        category: ['adventure','action','comedy','fantasy'],
        aboutEn: 'A twelve-year-old boy named Ali is not distinguished by special perseverance and hard work, which is why he gets solid threes at school, but one day everything changes: the boy finds an unusual gadget. It soon turns out that the mysterious device belongs to the secret spy agency MSS, and the main character himself is invited to study and further serve as a special agent. The guy agrees, and to the surprise of others, he makes every effort to become the best spy of the organization and save his native Cyber Territory from constant attacks by evil mercenaries and scientists.',
        aboutRu: 'Двенадцатилетний паренёк по имени Али не отличается особым упорством и трудолюбием, из-за чего в школе он получает сплошные тройки, однако в один прекрасный день все меняется: мальчик находит необычный гаджет. Вскоре выясняется, что таинственное устройство принадлежит секретному шпионскому агентству МСС, а самого главного героя приглашают на обучение и дальнейшую службу в качестве спецагента. Парень соглашается, и к удивлению для окружающих, прилагает все усилия, чтобы стать лучшим шпионом организации и спасти родную Киберраю от постоянных атак злых наемников и ученых.',
        rating: 4.6
    },
    {
        id: 15,
        nameEn: 'Detective Finnic',
        nameRu: 'Детектив Финник',
        imgSm: 'detectiv-finnic-min.jpg',
        imgLg: 'detectiv-finnic-md.jpg',
        video: '«Детектив Финник» — 25 декабря в 12_00 на СТС!.mp4',
        duration: 7,
        year: 2022,
        type: 'cartoon',
        director: 'Ilya Maximov',
        actors: ['Mixail Xrustalev', 'Veronica Golubeva','Ivan Chaban'],
        category: ['adventure','comedy','family'],
        aboutEn: 'Berg is a small European city, which has everything for a comfortable life: the film industry, the famous rock band "Canned Food" and even its own superhero, a fluffy brownie named Finnick. The latter lives under the same roof with schoolgirl Kristina and her parents. An inquisitive girl who has a craving for detective investigations helps the brownie to keep the peace in the city. Together they hunt down intruders, hunt monsters, protect the weak, restore justice and perform many other heroic deeds.',
        aboutRu: 'Берг — небольшой европейский город, в котором присутствует все для комфортной жизни: киноиндустрия, знаменитая рок-группа «Консервы» и даже свой супергерой, — пушистый домовой по имени Финник. Последний проживает под одной крышей со школьницей Кристиной и ее родителями. Любознательная девочка, имеющая тягу к детективным расследованиям, помогает домовому оберегать спокойствие в городе. Вместе они выслеживают злоумышленников, охотятся на монстров, защищают слабых, восстанавливают справедливость и совершают многие другие героические поступки.',
        rating: 4.8
    },
    {
        id: 16,
        nameEn: 'Shrek',
        nameRu: 'Шрэк',
        imgSm: 'shrek-min.jpeg',
        imgLg: 'shrek-md.jpeg',
        video: 'Shrek Trailer.mp4',
        duration: 90,
        year: 2001,
        type: 'cartoon',
        director: 'Andrew Adamson',
        actors: ['Mike Myers','Eddie Murphy','Cameron Diaz','John Lithgow'],
        category: ['adventure','comedy','family'],
        aboutEn: 'Somewhere in the swampy area lives a green giant, a scary ogre named Shrek. He scares the inhabitants of the fairy kingdom so that they do not disturb his usual peace. But one day, Lord Farquaad, the ruler of Duloc, expels all the fabulous inhabitants from his lands into the forest, removing them away from human eyes. Now Shrek\'s house is filled with a whole crowd of homeless people: Cookie, Little Red Riding Hood, Pinocchio, three little pigs, a talking Donkey and other fabulous characters. Angry, Shrek decides to deal with the intruder of his peace of mind, and return all the fabulous creatures back to their homes. To do this, he goes to Farquaad. Along with him, the chatty, ever-annoying Shrek is a talking Donkey, whom Shrek has already saved from the ruler\'s soldiers once. This is where their adventures begin, in which Shrek will have to expose the plans of the lord, return his swamp, and, of course, save the beautiful princess Fiona.',
        aboutRu: 'Где-то в болотистой местности живет зеленый великан, страшный огр по имени Шрек. Он пугает жителей сказочного королевства, чтобы они не нарушали его привычный покой. Но однажды лорд Фаркуад, правитель Дюлока, выгоняет со своих земель всех сказочных жителей в лес, убрав их подальше от людских глаз. Теперь дом Шрека наполнен целой толпой бездомных: Печенюшка, Красная шапочка, Пиноккио, три поросенка, говорящий Осёл и прочие сказочные персонажи. Разозлившись, Шрек решает разобраться с нарушителем его спокойствия, и вернуть обратно в свои дома всех сказочных существ. Для этого он отправляется к Фаркуаду. Вместе с ним увязывается болтливый, вечно надоедающий Шреку говорящий Осёл, которого Шрек один раз уже спас от солдат правителя. Здесь и начинаются их приключения, в которых Шреку предстоит разоблачить планы лорда, вернуть свое болото, и, конечно же, спасти прекрасную принцессу Фиону.',
        rating: 4.8
    },
    {
        id: 17,
        nameEn: 'Ju bing chang cheng chuan / The Great Warrior Wall',
        nameRu: 'Волчонок Сиа: Страж Великой стены воинов',
        imgSm: 'ju-bing-change-cheng-chuan-min.jpg',
        imgLg: 'ju-bing-change-cheng-chuan-md.jpg',
        video: 'Siya Wolf （The Great Warrior Wall） PV.mp4',
        duration: 13,
        year: 2019,
        type: 'cartoon',
        director: 'Lu Bei',
        actors: ['Su Shanci','FenShen'],
        category: ['adventure','fantasy','action'],
        aboutEn: 'Being very young, this wolf cub lost his parents and miraculously survived in a family of herbivorous animals that could not pass by a suffering lonely baby. Gradually, the growing predator decides to repay the kind animals by protecting their native village from dangerous enemies. And although the main character\'s best friends, a charming bunny and a cheerful calf, are almost completely sure that no one is threatening their home, the brave wolf senses the danger coming from the cruel emperor and is ready to fight back against the army of creepy giants.',
        aboutRu: 'Будучи совсем маленьким, волчонок Сия лишился родных родителей и чудом выжил в семействе травоядных животных, которые не смогли пройти мимо страдающего одинокого малыша. Постепенно подрастающий хищник решает отплатить добрым животным, защищая их родную деревню от опасных врагов. И хотя лучшие друзья главного героя, очаровательный зайчонок и весёлый теленок, почти полностью уверены, что их дому никто не угрожает, смелый волк чует надвигающуюся со стороны жестокого императора опасность и готов дать отпор армии жутких великанов.',
        rating: 4.6
    },
    {
        id: 18,
        nameEn: 'Arthur et les enfants de la Table Ronde',
        nameRu: 'Артур и дети круглого стола',
        imgSm: 'arthur-et-les-enfants-de-la-table-ronde-min.jpg',
        imgLg: 'arthur-et-les-enfants-de-la-table-ronde-md.jpg',
        video: 'ARTHUR ET LES ENFANTS  DE LA TABLE RONDE  - Dès le 3 sept en exclu sur TéléTOON .mp4',
        duration: 12,
        year: 2018,
        type: 'cartoon',
        director: 'Jan Luk Francua',
        actors: ['Rudi James Jephcott','Kaycie Chase','Tristan Bowles','Andy Chase'],
        category: ['adventure'],
        aboutEn: 'Arthur is a brave and intelligent prince who lives in a majestic castle, where his just and honest father, King Uther, rules. One day, the boy and his friends — Tristan, Guinevere, Sagramore and Gawain — become the organizers of a community called the Brotherhood of the Round Table. The members of the community adhere to high standards: they are faithful to the ideals of chivalry, and also try to remain fair, show solidarity and help those in need. Pursuing dreams of a better future for the inhabitants of their native country, the heroes embark on adventures, including battles with villains, the search for the missing fairy and even the rescue of the king.',
        aboutRu: 'Артур — отважный и смышленый принц, который живет в величественном замке, где правит его справедливый и честный отец — король Утер. Однажды мальчишка и его друзья — Тристан, Гиневер, Саграмор и Гавейн — становятся организаторами сообщества, получившего название Братство круглого стола. Члены сообщества придерживаются высоких стандартов: они верны рыцарским идеалам, а также стараются оставаться справедливыми, проявлять солидарность и оказывать помощь нуждающимся. Преследуя мечты о лучшем будущем для жителей родной страны, герои отправляются навстречу приключениям, включая сражения со злодеями, поиски пропавшей феи и даже спасение короля.',
        rating: 3.9
    },
    {
        id: 18,
        nameEn: 'The Lion King',
        nameRu: 'Король Лев',
        imgSm: 'the-lion-king-min.jpeg',
        imgLg: 'the-lion-king-md.jpeg',
        video: 'Трейлер КОРОЛЬ ЛЕВ (Trailer Lion King).wmv.mp4',
        duration: 88,
        year: 1994,
        type: 'cartoon',
        director: 'Roger Alles',
        actors: ['Matthew Broderick','Jeremy Irons','James Earl Jones','Whoopi Goldberg'],
        category: ['drama','adventure','family'],
        aboutEn: 'The cartoon takes place somewhere in the distant African savannah, where the great and noble king Mufasa, the head of the local lion pride, rules. All the animals are rejoicing, because their king has an heir, who is called Simba. And only Mufasa\'s own brother, Scar, who by all means longs to become king, is not at all happy about this news. He begins to make a plan to get rid of Mufasa and his baby at the same time. Very soon, the young Simba will know the full weight of loss and betrayal, as well as go into forced exile. But even away from home, he not only finds new friends, but also finds the determination to restore justice and take his rightful place.',
        aboutRu: 'Действия мультфильма разворачиваются где-то в далекой африканской саванне, где правит великий и благородный король Муфаса, глава местного львиного прайда. Все звери ликуют, ведь у их короля родился наследник, которого называют Симба. И только родной брат Муфасы – Шрам, который во что бы то ни стало жаждет стать королем, совсем не рад этой новости. Он начинает строить план, как одновременно избавиться от Муфасы и его малыша. Уже совсем скоро юный Симба познает всю тяжесть утраты и предательства, а также отправится в вынужденное изгнание. Но даже вдали от дома он не только находит новых друзей, но и обретает решимость восстановить справедливость и занять свое законное место.',
        rating: 5
    },
    {
        id: 19,
        nameEn: 'The fixik: New',
        nameRu: 'Фиксики. Новенькие',
        imgSm: 'fixik-new-min.jpg',
        imgLg: 'fixik-new-md.jpg',
        video: '«Фиксики. Новенькие» — смотрите 4 сезон сериала на нашем канале   новые серии на КиноПоискHD!.mp4',
        duration: 6,
        year: 2020,
        type: 'cartoon',
        director: 'Ivan Pshonkin',
        actors: ['Anastasia Dyatlova','Yaroslav Efremenko','Artem Skosarev'],
        category: ['fantasy','comedy','adventure','family'],
        aboutEn: 'The animated series continues to follow the adventures of a restless 9-year–old boy DimDimych and his classmate, a brave and persistent excellent student named Katya, who keep the secret of the existence of fixies - mysterious little people living in a variety of household appliances and helping to keep mechanical and electronic equipment in order. In addition to the usual friends of the main characters, Simka, Nolik, Masi, Papus and Dedus, new fixies appear in the plot, the hooligan twins Geek and Freak, as well as their adopted grandmother Basia.',
        aboutRu: 'Мультсериал продолжает следить за приключениями непоседливого 9-летнего мальчика ДимДимыча и его одноклассницы, смелой и настойчивой отличницы по имени Катя, которые хранят секрет существования фиксиков – таинственных маленьких человечков, живущих в самых разных бытовых приборах и помогающих содержать механическую и электронную технику в порядке. Помимо привычных друзей главных героев, Симки, Нолика, Маси, Папуса и Дедуса, в сюжете появляются новые фиксики, близнецы-хулиганы Гик и Фрик, а также их приемная бабушка Бася.',
        rating: 3.6
    },
    {
        id: 19,
        nameEn: 'Partly Cloudy',
        nameRu: 'Переменная облачность',
        imgSm: 'partly-cloudy-min.jpg',
        imgLg: 'partly-cloudy-md.jpg',
        video: 'Partly Cloudy - Trailer.mp4',
        duration: 6,
        year: 2009,
        type: 'cartoon',
        director: 'Pitter Sun',
        actors: ['Tony Fucile','Lori Richardson'],
        category: ['fantasy','comedy','family'],
        aboutEn: 'A stunning, kind cartoon "Partly Cloudy" (Partly Cloudy) will delight little kids and adults, too, will not leave them indifferent. It touches deeply hidden emotional strings and tells about friendship and love. We are taught here that a friend is known in trouble. We are faced with a fabulous, very colorful story about a mischievous cloud. We are told the secret that it turns out that the clouds make the kids, and they work in pairs with storks, who then carry them home. There is one cute, fluffy, but slightly harmful cloud in the sky, and it is this cloud that makes cocky and wayward bully kids. Moreover, he has his own personal assistant and a devoted stork friend. Everything is so sweet and cool. You can pick up a million epithets, but it\'s better to see once than hear a hundred times. Although the cartoon does not last long, so much warmth, kindness, tenderness and radiant light penetrates into the soul in these few minutes that some other cartoons do not give even an hour of viewing. The Disney studio always produces masterpieces and this is one of the best. Recommended for family viewing.',
        aboutRu: 'Потрясающий, добрый мультфильм "Переменная облачность" (Partly Cloudy) приведет маленьких детишек в восторг и взрослых тоже не оставит равнодушными. Он затрагивает спрятанные глубоко душевные струны и повествует о дружбе и любви. Нас учат здесь, что друг познаются в беде. Перед нами предстает сказочная, очень красочная история про озорное облако. Нам раскрывают тайну, что оказывается детишек делают облака, причем они работают в паре с аистами, которые после разносят их по домам. На небе есть одно милое, пушистое, но немного вредное облако и именно оно делает дерзких и своенравных ребятишек-забияк. Причем у него есть свой личный помощник и преданный друг — аист. Все так умильно и классно. Можно подобрать миллион эпитетов, но лучше один раз увидеть, чем сто раз услышать. Мультфильм хоть и идет не долго, но в душу проникает столько теплоты, добры, нежности и лучистого света, за эти несколько минут, что некоторые другие мультики не дарят и за час просмотра. У студии Дисней всегда получаются шедевры и это один из лучших. Рекомендован к семейному просмотру.',
        rating: 4.8
    },
    {
        id: 20,
        nameEn: 'Klaus',
        nameRu: 'Клаус',
        imgSm: 'klaus-min.jpg',
        imgLg: 'klaus-md.jpg',
        video: 'Klaus _ Official Trailer _ Netflix.mp4',
        duration: 98,
        year: 2019,
        type: 'cartoon',
        director: 'Sergio Pablos',
        actors: ['Jason Schwartzman','J.K. Simmons','Rashida Jones','Will Sasso'],
        category: ['comedy','adventure','family'],
        aboutEn: 'When the selfish and lazy son of a rich tycoon, Jesper, fails his studies at the mail academy, deservedly becoming the worst student, the guy\'s father sends him for re-education to a remote island in the Arctic circle. To return home and enjoy the benefits of his father\'s fortune, Jasper has to send six thousand letters, but soon he discovers that the locals, divided into two opposing camps, do not use postal services at all. Jesper, annoyed by another failure, is about to admit the mission is impossible, but suddenly finds allies in the face of teacher Alva and the mysterious lumberjack Klaus…',
        aboutRu: 'Когда эгоистичный и ленивый сын богатого магната Джеспер проваливает обучение в академии почты, заслуженно становясь худшим студентом, отец парня отправляет его на перевоспитание на удаленный остров за полярным кругом. Чтобы вернуться домой и пользоваться благами отцовского состояния, Джесперу предстоит отправить шесть тысяч писем, однако вскоре он обнаруживает, что местные жители, разделенные на два противоборствующих лагеря, вообще не пользуются почтовыми услугами. Джеспер, раздосадованный очередной неудачей, собирается признать миссию невыполнимой, но неожиданно находит союзников в лице учительницы Альвы и таинственного лесоруба Клауса…',
        rating: 4.7
    },
    {
        id: 21,
        nameEn: 'Ejen Ali the Movie',
        nameRu: 'Агент Али. Фильм',
        imgSm: 'ejen-ali-the-movie-min.jpg',
        imgLg: 'ejen-ali-the-movie-md.jpg',
        video: 'Ejen Ali The Movie - Official Trailer .mp4',
        duration: 97,
        year: 2019,
        type: 'cartoon',
        director: 'Muhammad Usamah Zaid',
        actors: ['Ida Rahayu','Noorhayati Maslini','Shafiq Isa','Azman Zulkiply'],
        category: ['comedy','adventure','family','action'],
        aboutEn: 'After being accidentally recruited as a spy, 12-year-old Agent Ali grew up and began working for a secret agency to protect the futuristic city of Cyberria from external threats.',
        aboutRu: 'После того, как его случайно завербовали в качестве шпиона, 12-летний агент Али вырос и стал работать в секретном агентстве, чтобы защитить футуристический город Киберрия от внешних угроз.',
        rating: 4.6
    },
    {
        id: 22,
        nameEn: 'Les Sisters',
        nameRu: 'Сестры',
        imgSm: 'les-sisters-min.jpg',
        imgLg: 'les-sisters-md.jpg',
        video: 'LES SISTERS - Bande-annonce.mp4',
        duration: 11,
        year: 2019,
        type: 'cartoon',
        director: 'Luk Vinchiguera',
        actors: ['Emmanuel Garijo','Kelly Marot'],
        category: ['comedy','family'],
        aboutEn: 'The animated series tells about the daily life of two sisters who live with their parents in a quiet suburb. 7-year–old Marie is just a child, fond of toys, outdoor games and having an army of devoted friends. 13-year-old Wendy is her complete opposite, as she already shows interest in boys and strives to imitate adults in everything, which is why she regularly becomes a victim of her naivety and inexperience. Nevertheless, frequent quarrels do not prevent both sisters from supporting each other in difficult times and realizing their crazy ideas.',
        aboutRu: 'Мультсериал повествует о повседневной жизни двух сестер, которые живут с родителями в тихом пригороде. 7-летняя Мари – совсем еще ребенок, увлекающаяся игрушками, подвижными играми и имеющая армию преданных подруг. 13-летняя Венди является ее полной противоположностью, так как уже проявляет интерес к мальчикам и во всем стремится подражать взрослым, из-за чего регулярно становится жертвой своей наивности и неопытности. Тем не менее частые ссоры не мешают обеим сестрам поддерживать друг друга в трудную минуту и реализовывать свои сумасшедшие идеи.',
        rating: 4.6
    },
    {
        id: 23,
        nameEn: 'Paperman',
        nameRu: 'Бумажный роман',
        imgSm: 'paperman-min.jpg',
        imgLg: 'paperman-md.jpg',
        video: 'Paperman TRAILER 1 (2012) - Oscar-Nominated Disney Animation Short HD.mp4',
        duration: 7,
        year: 2012,
        type: 'cartoon',
        director: 'John Kahrs',
        actors: ['John Kahrs','Kari Wahlgren','Jack Goldenberg'],
        category: ['drama','family'],
        aboutEn: 'The short film tells about a lonely young man from New York in the middle of the last century, whose fate takes an unexpected turn after a chance meeting with a beautiful woman during a morning trip. A guy falls in love with a girl at first sight, but accidentally misses her and decides that he has lost her forever. However, he gets a second chance when he sees her in the window of a skyscraper opposite his office. Only imagination and a stack of papers help a guy to attract a girl\'s attention. However, this is nothing compared to what fate has prepared for the couple.',
        aboutRu: 'Короткометражка расскажет об одиноком молодом человеке из Нью-Йорка середины прошлого века, чья судьба принимает неожиданный оборот после случайной встречи с красивой женщиной во время утренней поездки. Парень влюбляется в девушку с первого взгляда, но случайно упускает её и решает, что потерял её навсегда. Однако он получает второй шанс, когда видит её в окне небоскреба напротив своего офиса. Только воображение и стопка бумаг помогают парню привлечь внимание девушки. Однако это не идёт ни в какое сравнение с тем, что для пары приготовила судьба.',
        rating: 4.7
    },
    {
        id: 24,
        nameEn: 'Miniforce X',
        nameRu: 'Минифорс X',
        imgSm: 'miniforce-x-min.jpg',
        imgLg: 'miniforce-x-md.jpg',
        video: 'miniforce-x.mp4',
        duration: 13,
        year: 2018,
        type: 'cartoon',
        director: 'Youngjun Lee',
        actors: ['Um Sang-Hyun','Lee So-Yeong','Jeon Tae-Yeol'],
        category: ['fantasy','adventure'],
        aboutEn: 'The most important villain of the universe named Zenos joins an alliance with a gang of space pirates and wants to restore his lost power. The main source of energy for him is negative emotions, such as sadness or fear, which are produced by living beings. Having studied the nearest planets, Zenos chooses Earth as his target, where he intends to cause negative emotions in people with the help of chaos and disasters created by him. The Mini Force team consisting of the fearless Volta, the Family, Max and Lucy, living under the same roof with the girl Susie, stand up to protect the Earth.',
        aboutRu: 'Самый главный злодей Вселенной по имени Зенос вступает в союз с бандой космических пиратов и хочет восстановить утраченную силу. Основным источником энергии для него выступают негативные эмоции, такие как печаль или страх, которые вырабатывают живые существа. Изучив ближайшие планеты, Зенос выбирает своей целью Землю, где с помощью созданных им хаоса и бедствий намеревается вызывать у людей отрицательные эмоции. Команда Минифорс в составе бесстрашных Вольта, Сэмми, Макса и Люси, живущих под одной крышей с девочкой Сьюзи, встают на защиту Земли.',
        rating: 4.7
    },
    {
        id: 25,
        nameEn: 'Masha and Bear',
        nameRu: 'Маша и Медведь.',
        imgSm: 'masha-medved-min.jpg',
        imgLg: 'masha-medved-md.jpg',
        video: 'happy-bd-masha.mp4',
        duration: 3,
        year: 2021,
        type: 'cartoon',
        director: 'Oleg Kuzovkov',
        actors: ['Boris Kutnevich','Boris Kutnevich','Kaitlyn McCormick'],
        category: ['comedy'],
        aboutEn: 'Sing with Masha and the Bear the most favorite songs from the legendary cartoon, as well as real hits of the Russian pop.',
        aboutRu: 'Пой с Машей и Медведем самые любимые песенки из легендарного мультфильма, а также настоящие хиты отечественной эстрады.',
        rating: 4.9
    },
    {
        id: 26,
        nameEn: 'Soul',
        nameRu: 'Душа',
        imgSm: 'soul-min.jpg',
        imgLg: 'soul-md.jpg',
        video: 'Disney and Pixar’s Soul _ Official Trailer _ Disney+.mp4',
        duration: 100,
        year: 2020,
        type: 'cartoon',
        director: 'Pete Docter',
        actors: ['Jamie Foxx','Tina Fey','Graham Norton','Rachel House'],
        category: ['comedy','fantasy','drama','adventure','family'],
        aboutEn: 'Josh Gardner works as a music teacher at a New York high school, although he always dreamed of playing jazz on the big stage, which his seamstress mother Libba opposed, fearing for their financial well-being. Once, at an audition at a club, having impressed jazz star Dorothea Williams with his talent, he finds himself one step away from realizing his cherished dream, but his life tragically ends on the same day when a man falls through an open hatch. Finding himself in a parallel dimension in the form of an incorporeal soul, the main character is looking for a way to return to the world of the living, which leads him to meet a stubborn soul named "22"...',
        aboutRu: 'Джо Гарднер работает учителем музыки в одной из средних школ Нью-Йорка, хотя всегда мечтал играть джаз на большой сцене, чему противилась его мать-швея Либба, опасающаяся за их финансовое благополучие. Однажды на прослушивании в клубе впечатлив своим талантом джазовую звезду Доротею Уильямс, он оказывается в одном шаге от реализации заветной мечты, но его жизнь трагически обрывается в тот же день, когда мужчина проваливается в открытый люк. Очутившись в параллельном измерении в виде бестелесной души, главный герой ищет способ вернуться в мир живых, что приводит его к знакомству с упрямой душой, носящей имя «22»...',
        rating: 4.4
    },
    {
        id: 27,
        nameEn: 'WALL·E',
        nameRu: 'ВАЛЛ·И',
        imgSm: 'walle-min.jpg',
        imgLg: 'walle-md.jpg',
        video: 'wall-e.mp4',
        duration: 98,
        year: 2008,
        type: 'cartoon',
        director: 'Ben Burtt',
        actors: ['Ben Burtt','Jeff Garlin','Jennifer Hale','Elissa Knight'],
        category: ['family','fantasy','adventure'],
        aboutEn: 'The action takes place in the distant future, when people left the Earth, and the once prosperous planet turned into a giant landfill. The plot centers on WALL-I, a sanitary robot living on an abandoned planet in proud solitude, who has collected a collection of various things — from lighters to an old iPod model. One day, a spaceship arrives on Earth and leaves a beautiful and modern probe named EVA on the planet to find a living plant, which is being cared for by WALL-I. Pretty soon, the main character falls madly in love with EVE, after which their grandiose space adventures begin…',
        aboutRu: 'Действие разворачивается в далеком будущем, когда люди покинули Землю, а некогда процветающая планета превратилась в гигантскую свалку. В центре сюжета находится ВАЛЛ-И — санитарный робот, живущий на заброшенной планете в гордом одиночестве, который собрал коллекцию различных вещей — от зажигалок до старой модели iPod. Однажды на Землю прилетает космический корабль и оставляет на планете красивый и современный зонд по имени ЕВА, чтобы найти живое растение, за которым ухаживает ВАЛЛ-И. Довольно скоро главный персонаж без памяти влюбляется в ЕВУ, после чего начинаются их грандиозные космические приключения…',
        rating: 4.6
    },
    {
        id: 28,
        nameEn: 'Zootopia',
        nameRu: 'Зверополис',
        imgSm: 'zootopia-min.jpg',
        imgLg: 'zootopia-md.jpg',
        video: 'Zootopia as a Crime Thriller - Trailer Mix.mp4',
        duration: 108,
        year: 2016,
        type: 'cartoon',
        director: 'Byron Howard',
        actors: ['Ginnifer Goodwin','Jason Bateman','Idris Elba','Jenny Slate'],
        category: ['comedy','criminal','adventure','family'],
        aboutEn: 'Welcome to the wonderful world in which people never appeared, so a huge advanced civilization, very similar to modern human, was built by various animals, which in the process of evolution developed to the level of a modern inhabitant of a megalopolis.\n' +
            'The action of the fascinating cartoon will take place in the huge city of Zveropolis – a place where animals of all kinds, whether they are predators or herbivores, live in peace and harmony, doing, like you and me, the daily hustle and bustle.\n' +
            'In the center of the plot will be Judith Hops – the first rabbit in Zveropolis, accepted into the ranks of the valiant police, which immediately caused a lot of skeptical comments, both from the press and from the population. It is quite expected that none of the colleagues at work took the new girl seriously, and the harsh chief of police gave her the simplest and most routine outfit when distributing duties. But full of optimism and childish enthusiasm, Judith does not lose heart – enlisting the support of her new friend, petty crook Nick Wilde, she is ready to prove that despite their size and physical characteristics, rabbits can not only stand up for themselves, but also fully stand up for citizens.',
        aboutRu: 'Добро пожаловать в удивительный мир, в котором люди так и не появились, поэтому огромную продвинутую цивилизацию, очень похожую на современную человеческую, построили различные звери, в процессе эволюции развившиеся до уровня современного жителя мегаполиса.\n' +
            'Действия увлекательного мультфильма будут происходить в огромном городе Зверополис – месте, где звери всевозможных видов, будь они хищниками или травоядными, живут в мире и согласии, занимаясь, как и мы с вами, повседневной суетой.\n' +
            'В центре сюжета окажется Джудит Хопс – первая в Зверополисе крольчиха, принятая в стройные ряды доблестной полиции, что сразу же вызвало массу скептических комментариев, как со стороны прессы, так и со стороны населения. Вполне ожидаемо, что никто из коллег по работе не воспринял новенькую всерьёз, а суровый шеф полиции при распределении обязанностей выдал ей самый простой и рутинный наряд. Но полная оптимизма и ребяческого задора Джудит не унывает – заручившись поддержкой своего нового знакомого, мелкого жулика Ника Уайлда, она готова доказать, что несмотря на свои размеры и физические данные, кролики могут не только за себя постоять, но и в полной мере стать на защиту граждан.',
        rating: 4.3
    },
    {
        id: 29,
        nameEn: 'Sing 2',
        nameRu: 'Зверопой 2',
        imgSm: 'sing-2-min.jpg',
        imgLg: 'sing-2-md.jpg',
        video: 'ЗВЕРОПОЙ 2 _ Трейлер 3 _ В кино с 23 декабря.mp4',
        duration: 112,
        year: 2021,
        type: 'cartoon',
        director: 'Garth Jennings',
        actors: ['Matthew McConaughey','Reese Witherspoon','Scarlett Johansson','Tori Kelly'],
        category: ['comedy','adventure','family'],
        aboutEn: 'Buster Moon has created a successful theater, but Jimmy\'s producer refuses to put on his new show. Determined to prove his worth, koala, along with the artists, goes to the Red Shore City resort to get inspiration. Soon Buster decides to impress Jimmy and promises that rock star Clay Calloway will appear in his new production. Jimmy falls for the idea, offering three weeks for rehearsals and a room in the theater. Now Buster needs to figure out how to contact Clay and persuade him to return to the stage. Meanwhile, other theater artists are experiencing problems: Mina is afraid to kiss a colleague on stage, Johnny cannot cope with the choreography, and the role of Rosita is given to Jimmy\'s daughter...',
        aboutRu: 'Бастер Мун создал успешный театр, но продюсер Джимми отказывается ставить его новое шоу. Решив доказать свою состоятельность, коала вместе с артистами отправляется на курорт Редшор-Сити, чтобы подчерпнуть вдохновения. Вскоре Бастер решает впечатлить Джимми и обещает, что рок-звезда Клэй Кэллоуэй появится в его новой постановке. Джимми клюет на идею, предлагая три недели на репетиции и помещение в театре. Теперь Бастеру нужно придумать, как связаться с Клэем и уговорить его вернуться на сцену. Тем временем другие артисты театра переживают проблемы: Мина боится поцеловать коллегу по сцене, Джонни не может справиться с хореографией, а роль Розиты отдают дочери Джимми...',
        rating: 3.9
    },
    {
        id: 30,
        nameEn: 'Beauty and the Beast',
        nameRu: 'Красавица и чудовище',
        imgSm: 'beauty-and-the-beast-min.jpg',
        imgLg: 'beauty-and-the-beast-md.jpg',
        video: 'Beauty and the Beast (1991) Trailer #1 _ Movieclips Classic Trailers.mp4',
        duration: 84,
        year: 1991,
        type: 'cartoon',
        director: 'Gary Trousdale',
        actors: ['Paige O\'Hara','Robby Benson','Jesse Corti','Rex Everhart'],
        category: ['fantasy','family'],
        aboutEn: 'Selfish Prince Adam was cursed by a mysterious enchantress who turned him into a terrible Monster. To get rid of the curse, the prince will not only have to fall in love with a young girl, but also achieve her love, and only then will he be able to atone for his guilt. Ten years later, he gets a chance to return to his true form when the charming Belle offers to take the place of her father Maurice as a prisoner of the Monster. So begins the amazing adventure of Belle and the Monster, who are destined to go through a series of trials together...',
        aboutRu: 'Эгоистичный принц Адам был проклят таинственной чародейкой, которая превратила его в страшное Чудовище. Чтобы избавиться от проклятия, принцу предстоит не только полюбить юную девушку, но и добиться ее любви, и лишь тогда он сможет искупить свою вину. Десять лет спустя у него появляется шанс вернуть истинный облик, когда очаровательная Белль предлагает занять место своего отца Мориса в качестве пленника Чудовища. Так начинается удивительное приключение Белль и Чудовища, которым вместе суждено пройти через серию испытаний...',
        rating: 4.9
    },
]