import { I_FilmsApi } from "../../models/server/films/interfaces.ts";

export const allFilmsApi: I_FilmsApi[] = [
  {
    id: 0,
    nameEn: "Ghostbusters: Frozen Empire",
    nameRu: "Охотники за Приведениями: Леденящий ужас",
    imgSm: "ghostbusters-min.jpg",
    imgLg: "ghostbusters-md.jpg",
    video:
      "Охотники за привидениями_ Леденящий ужас — Русский дублированный трейлер .mp4",
    duration: 109,
    year: 2024,
    type: "movie",
    director: "Gil Kenan",
    actors: [
      "Paul Rudd",
      "Carrie Coon",
      "Mckenna Grace",
      "Finn Wolfhard",
      "Kumail Nanjiani",
      "Patton Oswalt",
      "Celeste O'Connor",
      "Logan Kim",
    ],
    category: ["fantasy", "comedy", "adventure"],
    aboutEn:
      "After the events in Oklahoma, the Spengler family begins their new life in New York as ghost hunters, as a family, as teenagers and parents. The discovery of an ancient artifact unleashes an evil force. Ghostbusters new and old must join forces to protect their home and save the world from a second ice age.\n",
    aboutRu:
      "После событий в Оклахоме семья Шпенглеров начинает свою новую жизнь в Нью-Йорке как охотники за привидениями, как семья, как подростки и родители. Обнаружение древнего артефакта высвобождает злую силу. Новые и старые Охотники за привидениями должны объединить усилия, чтобы защитить свой дом и спасти мир от второго ледникового периода.",
    rating: 4.9,
  },
  {
    id: 1,
    nameEn: "Monkey Man",
    nameRu: "Манкимэн",
    imgSm: "monkeyman-min.jpg",
    imgLg: "monkeyman-md.jpg",
    video: "Манкимэн _ Трейлер _ В кино с 11 апреля.mp4",
    duration: 121,
    year: 2024,
    type: "movie",
    director: "Dev Patel",
    actors: [
      "Dev Patel",
      "Sharlto Copley",
      "Jatin Malik",
      "Pitobash",
      "Sikandar Kher",
      "Sobhita Dhulipala",
      "Ashwini Kalsekar",
    ],
    category: ["action", "thriller", "criminal"],
    aboutEn:
      "The violent streets of Mumbai have made him a fighter who will stop at nothing to avenge his family. From now on, his life is divided between underground fights for money, where masked people fight until their last breath, and work in an elite nightclub for the richest and most vicious. Increasingly immersed in the secret world, he settles scores with crime bosses and corrupt politicians who take everything from people. His name is Monkeyman.\n",
    aboutRu:
      "Жестокие улицы Мумбаи сделали из него бойца, который не остановится ни перед чем, чтобы отомстить за свою семью. Отныне его жизнь делится между подпольными боями за деньги, где люди в масках дерутся до последнего вдоха, и работой в элитном ночном клубе для самых богатых и самых порочных. Всё больше погружаясь в тайный мир, он сводит счёты с криминальными авторитетами и коррумпированными политиками, отнимающими у людей всё. Имя ему — Манкимэн.",
    rating: 4.2,
  },
  {
    id: 2,
    nameEn: "Dune: Part Two",
    nameRu: "Дюна: Часть вторая",
    imgSm: "duna-min.jpg",
    imgLg: "duna-md.jpg",
    video: "Дюна 2 _ Русский трейлер (Дубляж) _ 2023 _ Dune_ Part Two.mp4",
    duration: 165,
    year: 2024,
    type: "movie",
    director: "Denis Villeneuve",
    actors: [
      "Timothée Chalamet",
      "Zendaya",
      "Javier Bardem",
      "Rebecca Ferguson",
      "Austin Butler",
      "Josh Brolin",
    ],
    category: ["fantasy", "action", "adventure", "drama"],
    aboutEn:
      "The young Duke Paul Atreides, who has the gift of clairvoyance, miraculously survives the assassination attempt on his family, after which, together with his mother, Lady Jessica, he hides from persecution in the endless desert. The two find safe refuge in the camp of the Fremen - a freedom-loving people who, over many centuries, have adapted to life in the harsh conditions of the planet Arrakis. Paul meets his love there, Chani, tries to take revenge on the conspirators for the murder of his family, and also accepts his destiny as the Kwisatz Haderach - the messiah who needs to lead humanity to a better future.\n",
    aboutRu:
      "Молодой герцог Пол Атрейдес, обладающий даром ясновидения, чудом переживает покушение на свою семью, после чего вместе с матерью, леди Джессикой, скрывается от преследования среди бескрайней пустыни. Двое находят безопасное убежище в лагере фрименов — свободолюбивого народа, который за многие столетия приспособился к жизни в суровых условиях планеты Арракис. Пол встречает там свою любовь по имени Чани, пытается отомстить заговорщикам за убийство семьи, а также принимает свою судьбу Квисатц Хадераха — мессии, которому необходимо привести человечество к лучшему будущему.",
    rating: 4.2,
  },
  {
    id: 3,
    nameEn: "Damsel",
    nameRu: "Дева и дракон",
    imgSm: "maiden-and-dragon-min.jpg",
    imgLg: "maiden-and-dragon-md.jpg",
    video: 'Девица. Официальный трейлер.mp4',
    duration: 113,
    year: 2024,
    type: "movie",
    director: 'Juan Carlos Fresnadillo',
    actors: ['Millie Bobby Brown','Ray Winstone','Brooke Carter','Angela Bassett','Robin Wright','Nick Robinson'],
    category: ["fantasy", "adventure", "action"],
    aboutEn: 'The film takes place in the Wild West in 1870. Young Samuel Alabaster, a wealthy pioneer, sets out on a daring journey to marry the beautiful Penelope, the love of his life. On the road, he is accompanied by a drunkard, Parson Henry, posing as a priest, and a miniature horse named Toffee. As the group traverses the Wild West, the seemingly simple journey becomes more treacherous and complex, demonstrating the unpredictability of human emotions and blurring the lines between hero, villain and damsel.\n',
    aboutRu: 'Действие фильма разворачивается на Диком Западе в 1870 году. Молодой Самуэль Алебастр, богатый первопроходец, отправляется в отважное путешествие, чтобы жениться на прекрасной Пенелопе, любви всей своей жизни. В дороге компанию ему составляет пьяница Парсон Генри, выдающий себя за священника и миниатюрная лошадь по кличке Ириска. По мере того, как группа пересекает Дикий Запад, простое, на первый взгляд, путешествие становится более коварным и запутанным, демонстрируя непредсказуемость человеческих чувств и размывая границы между героем, злодеем и девицей.',
    rating: 4.6,
  },
  {
    id: 4,
    nameEn: "Road House",
    nameRu: "Дом у дороги",
    imgSm: "road-house-min.jpg",
    imgLg: "road-house-md.jpg",
    video: 'Дом у дороги — Русский трейлер (2024).mp4',
    duration: 123,
    year: 2024,
    type: "movie",
    director: 'Doug Liman',
    actors: ['Jake Gyllenhaal','Daniela Melchior','Conor McGregor','Billy Magnussen','Jessica Williams','B.K. Cannon','Joaquim de Almeida','Post Malone'],
    category: ["action", "thriller", "drama"],
    aboutEn: 'Bouncer Dalton arrives at a provincial bar, where he encounters a local gang. A remake of the 1989 film of the same name.\n',
    aboutRu: 'Вышибала Далтон приезжает в провинциальный бар, где сталкивается с местной бандой. Ремейк одноименного фильма 1989 года.',
    rating: 4.8,
  },
  {
    id: 5,
    nameEn: "Argylle",
    nameRu: "Аргайл: Супершпион",
    imgSm: "argylle-min.jpg",
    imgLg: "argylle-md.jpg",
    video: 'Argylle _ Official Trailer.mp4',
    duration: 139,
    year: 2024,
    type: "movie",
    director: 'Matthew Vaughn',
    actors: ['Henry Cavill','Bryce Dallas Howard','Sam Rockwell','Bryan Cranston','Daniel Singh','Dua Lipa','John Cena'],
    category: ["action", "thriller", "comedy"],
    aboutEn: 'Ellie Conway is a successful spy novelist who leads a secluded life, preferring to spend her free time with her cat Alfie. While traveling by train to visit her mother, Ellie meets Aidan, who introduces himself as a fan of her work, but is in fact a real spy. When a writer is assassinated on a train, Aiden comes to the rescue, and Ellie unexpectedly finds out that the powerful organization “Division” is hunting her, since her books are very reminiscent of the details of real spy operations...\n',
    aboutRu: 'Элли Конвей — успешная писательница шпионских романов, которая ведет замкнутый образ жизни, предпочитая проводить свободное время со своим котом Алфи. Отправляясь в путешествие на поезде, чтобы навестить маму, Элли встречает Эйдана, который представляется в качестве поклонника ее творчества, но на самом деле является настоящим шпионом. Когда на писательницу совершается покушение в поезде, Эйден приходит на помощь, а Элли неожиданно выясняет, что за ней охотится могущественная организация «Подразделение», поскольку ее книги очень сильно напоминают детали реальных шпионских операций...',
    rating: 4.3,
  },
  {
    id: 6,
    nameEn: "Spaceman / Spaceman of Bohemia",
    nameRu: "В космосе / Астронавт",
    imgSm: "spaceman-min.jpg",
    imgLg: "spaceman-md.jpg",
    video: 'В космосе — Русский трейлер (4К Дубляж 2024).mp4',
    duration: 109,
    year: 2024,
    type: "movie",
    director: 'Johan Renck',
    actors: ['Adam Sandler','Carey Mulligan','Paul Dano','Kunal Nayyar','Isabella Rossellini','Lena Olin','Petr Papánek'],
    category: ["adventure", "drama", "fantasy"],
    aboutEn: 'As part of an experimental program, Czech astronaut Jakub is all alone on board a spacecraft exploring the outer reaches of the solar system. After spending six months in space, he finds himself near Jupiter on a mission to study a mysterious nebula that can be seen on Earth. Approaching a strange cloud, the hero suddenly discovers a guest on his ship - the giant alien spider Hanus, who is able to read the astronaut\'s thoughts and is interested in learning details about his life...\n',
    aboutRu: 'В рамках экспериментальной программы чешский астронавт Якуб находится в полном одиночестве на борту космического корабля, исследующего внешние пределы Солнечной системы. Проведя шесть месяцев в космосе, он оказывается вблизи Юпитера, выполняя задачу по изучению загадочной туманности, которую можно увидеть на Земле. Приблизившись к странному облаку, герой внезапно обнаруживает на своем корабле гостя — гигантского инопланетного паука Хануса, способного читать мысли астронавта и заинтересованного узнать подробности о его жизни…',
    rating: 4.2,
  },
  {
    id: 7,
    nameEn: "The Beekeeper",
    nameRu: "Пчеловод",
    imgSm: "the-beekeeper-min.jpg",
    imgLg: "the-beekeeper-md.jpg",
    video: 'Пчеловод — Официальный русский трейлер (Дубляж, 2024).mp4',
    duration: 105,
    year: 2024,
    type: "movie",
    director: 'David Ayer',
    actors: ['Jason Statham','Emmy Raver-Lampman','Bobby Naderi','Josh Hutcherson','Jeremy Irons','David Witts','Michael Epp','Taylor James'],
    category: ["action", "thriller"],
    aboutEn: 'Adam Clay, a former secret agent for a secret organization called the Beekeepers, lives on a small farm in Massachusetts owned by an elderly retired teacher, Eloise Parker, where he helps her with housework and raises bees. One day, a woman falls victim to online scams and loses $2 million, prompting her to commit suicide. With the police powerless, Adam Clay takes justice into his own hands, mercilessly killing members of a gang of crooks one by one, intending to get to the very top. Meanwhile, FBI agent Verona Parker, the daughter of the late Eloise, seeks to stop the bloodshed.\n',
    aboutRu: 'Адам Клей, бывший секретный агент тайной организации под названием «Пчеловоды», живет на небольшой ферме в Массачусетсе, принадлежащей пожилой учительнице на пенсии Элоизе Паркер, где помогает ей по хозяйству и разводит пчел. Однажды женщина становится жертвой интернет-мошенников и теряет 2 миллиона долларов, что побуждает ее покончить жизнь самоубийством. Поскольку полиция оказывается бессильной, Адам Клей берет правосудие в свои руки, безжалостно убивая одного за другим членов банды мошенников, намереваясь добраться до самой верхушки. Тем временем агент ФБР Верона Паркер, являющаяся дочерью покойной Элоизы, стремится остановить кровопролитие.',
    rating: 5,
  },
  {
    id: 8,
    nameEn: "Dogman",
    nameRu: "Догмен",
    imgSm: "dogman-min.jpg",
    imgLg: "dogman-md.jpg",
    video: 'Догмен — Русский трейлер (2024).mp4',
    duration: 110,
    year: 2023,
    type: "movie",
    director: 'Luc Besson',
    actors: ['Caleb Landry Jones','Jojo T. Gibbs','Christopher Denham','Clemens Schick','John Charles Aguilar','Grace Palma','Iris Bry'],
    category: ["thriller", "action", "drama"],
    aboutEn: 'As a suspicious man in a wheelchair and wearing a blood-soaked suit, Douglas attracts the attention of the police, who discover a pack of dogs in his vehicle and several corpses in the detainee\'s permanent residence. While in custody, the man gradually tells Evelyn, a psychologist hired by the police, the story of his life and how he ended up in such a catastrophic situation. Douglas\'s past is marked by violence and isolation, and now the man lives surrounded by dogs, which he perceives as part of his family. A family ready to protect him in any situation, and a family for whose sake he crosses the line and becomes a violent criminal...\n',
    aboutRu: 'Будучи подозрительным человеком в инвалидной коляске и в пропитанном кровью костюме, Дуглас привлекает внимание полицейских, которые обнаруживают в его транспортном средстве стаю собак и несколько трупов в месте постоянного проживания задержанного. Находясь под стражей, мужчина постепенно рассказывает нанятому полицией психологу Эвелин историю своей жизни и то, как он оказался в столь катастрофической ситуации. Прошлое Дугласа отмечено насилием и изоляцией, а теперь мужчина живет в окружении собак, которых он воспринимает в качестве членов своей семьи. Семья, готовая защищать его в любых ситуациях, и семья, ради которой он пересекает грань и становится жестоким преступником…',
    rating: 4.5,
  },
  {
    id: 9,
    nameEn: "Aquaman and the Lost Kingdom",
    nameRu: "Аквамен и потерянное царство",
    imgSm: "aquaman-and-the-lost-kingdom-min.jpg",
    imgLg: "aquaman-and-the-lost-kingdom-md.jpg",
    video: 'Аквамен 2_ Потерянное царство — Русский трейлер (Дубляж, 2023).mp4',
    duration: 124,
    year: 2023,
    type: "movie",
    director: 'James Wan',
    actors: ['Jason Momoa','Patrick Wilson','Yahya Abdul-Mateen II','Amber Heard','Nicole Kidman','Randall Park','Temuera Morrison'],
    category: ["fantasy", "action", "adventure"],
    aboutEn: 'Having defeated his brother Orm and taken the throne of Atlantis, Arthur Curry married the beautiful Mera, who gave birth to his heir Arthur Jr. Since then, Aquaman has tried to combine life on land, where he spends time with his family and fights crime, and underwater, ruling as a king. Meanwhile, Black Manta, who has taken possession of an ancient trident with enormous destructive power, intends to defeat the king of Atlantis once and for all. To confront the powerful supervillain, Aquaman is forced to rescue Orm from prison and form an alliance with him.\n',
    aboutRu: 'Одолев своего брата Орма и заняв трон Атлантиды, Артур Карри женился на прекрасной Мере, которая родила ему наследника Артура-младшего. С тех пор Аквамен старается совмещать жизнь на суше, где проводит время с семьей и борется с преступностью, и под водой, правя как царь. Тем временем Черный Манта, завладевший древним трезубцем, имеющим огромную разрушительную силу, намеревается раз и навсегда победить царя Атлантиды. Чтобы противостоять могущественному суперзлодею, Аквамен вынужден вытащить из тюрьмы Орма и заключить с ним союз.',
    rating: 4.2,
  },
  {
    id: 10,
    nameEn: "Wonka",
    nameRu: "Вонка",
    imgSm: "wonka-min.jpg",
    imgLg: "wonka-md.jpg",
    video: 'WONKA _ Official Trailer.mp4',
    duration: 116,
    year: 2023,
    type: "movie",
    director: 'Paul King',
    actors: ['Timothée Chalamet','Gustave Die','Murray McArthur','Paul G. Raymond','Isy Suttie','Matilda Tucker'],
    category: ["fantasy", "adventure", "comedy", "musical", "family"],
    aboutEn: 'Dreaming of opening his own chocolate shop, Willy Wonka comes to the big city, ready to conquer the locals with his delicious chocolate. However, on his first day in the metropolis, Willie loses his personal savings and finds himself deeply in debt to the deceitful and vile laundress Mrs. Scrubbit. Forced to work off his debt at a laundromat, Wonka meets new friends and suddenly finds a way to make his dreams come true. But first he has to outwit the greedy chocolatiers and the local police chief...\n',
    aboutRu: 'Мечтая открыть собственный шоколадный магазин, Вилли Вонка приезжает в большой город, готовый покорить местных жителей своим изысканным шоколадом. Однако в первый же день в мегаполисе Вилли теряет личные сбережения и оказывается по уши в долгах перед лживой и подлой прачкой — миссис Скруббит. Вынужденный отрабатывать долг в прачечной самообслуживания, Вонка встречает новый друзей и внезапно находит способ воплотить заветные мечты в реальность. Но сперва ему предстоит перехитрить алчных шоколатье и начальника местной полиции…',
    rating: 4.8,
  },
  {
    id: 11,
    nameEn: "Lili David",
    nameRu: "Лили Давид",
    imgSm: "lili-david-min.jpg",
    imgLg: "lili-david-md.jpg",
    video: 'Lili David na kanale FilmBox.mp4',
    duration: 90,
    year: 2012,
    type: "movie",
    director: 'Christophe Barraud',
    actors: ['Julie-Anne Roth','Chantal Ladesou','Mathieu Delarive','Etienne Chicot'],
    category: ["comedy"],
    aboutEn: 'Lily David is 32 years old, she has a 12-year-old son and a new boss - the current wife of her ex-husband. Lily\'s job consists of fulfilling the wishes and whims of clients of the firm You4You, which specializes in organizing events of all kinds, from weddings and parties to hunting, and often clients\' requests are on the edge of the possible, be it an urgent search for a private jet or inviting Michael Jackson to someone\'s day. birth...\n',
    aboutRu: 'Лили Давид 32 года, у нее есть сын — 12-летний подросток и новый босс — теперешняя жена ее бывшего мужа. Работа Лили состоит в исполнении пожеланий и прихотей клиентов фирмы You4You, специализирующейся на организации мероприятий любого рода: от свадеб и вечеринок до охоты, и зачастую запросы клиентов оказываются на грани возможного, будь то срочный поиск частного самолета или приглашение Майкла Джексона на чей-то день рождения…',
    rating: 4.4,
  },
  {
    id: 12,
    nameEn: "The Green Mile",
    nameRu: "Зеленая миля",
    imgSm: "the-green-mile-min.jpg",
    imgLg: "the-green-mile-md.jpg",
    video: 'Зеленая миля трейлер на русском.mp4',
    duration: 189,
    year: 1999,
    type: "movie",
    director: 'Frank Darabont',
    actors: ['Tom Hanks','Michael Clarke Duncan','David Morse','Bonnie Hunt','James Cromwell'],
    category: ["drama", "fantasy", "criminal"],
    aboutEn: 'The film is based on the novel of the same name by Stephen King. One day, a new prisoner enters the death row block - John Coffey, convicted of murdering little girls. Coffey attracts the attention of the head of this block, Paul Edgecombe. Over the many years of work, he has seen enough of different criminals, and he understands a little about people. Paul doubts Coffey\'s guilt, because despite his terrifying appearance, he has kindness and humanity. It also turns out over time that John has an amazing gift - the ability to heal. Paul understands that such a person cannot possibly be a murderer. But what to do and how to help him?\n',
    aboutRu: 'Картина снята по одноименному роману Стивена Кинга. Однажды в блок для приговоренных к смертной казни поступает новый заключенный – Джон Коффи, осужденный за убийство маленьких девочек. Коффи привлекает внимание начальника этого блока – Пола Эджкомба. За долгие годы работы он насмотрелся на разных преступников, и он немного разбирается в людях. Пол сомневается в виновности Коффи, ведь несмотря на его устрашающий вид, он обладает добротой и человечностью. Так же со временем выясняется, что Джон является обладателем удивительного дара – способностью исцелять. Пол понимает, что такой человек никак не может быть убийцей. Но что же делать, и как помочь ему?',
    rating: 4.9,
  },
  {
    id: 13,
    nameEn: "Forrest Gump",
    nameRu: "Форрест Гамп",
    imgSm: "forrest-gump-min.jpg",
    imgLg: "forrest-gump-md.jpg",
    video: 'forrest-gump.mp4',
    duration: 142,
    year: 1994,
    type: "movie",
    director: 'Robert Zemeckis',
    actors: ['Tom Hanks','Robin Wright','Gary Sinise','Sally Field','Rebecca Williams','Michael Conner Humphreys'],
    category: ["drama"],
    aboutEn: 'Little Forrest lives with his mother in Alabama, in a town called Greenbow. He has health problems, and on top of everything else, the boy has an intellectual disorder, so his mother has to make a lot of efforts to get him into a regular school. At school, Forrest is constantly bullied by his peers, but this helps him learn to run very fast, which in the future gives the guy a chance to become a student and become one of the best amateur athletes in the country.\nAfter graduating from university, Forrest joins the army and finds himself in the outbreak of the Vietnam War...\n',
    aboutRu: 'Картина снята по мотивам одноименного романа Уинстона Грума. Сюжет фильма рассказывает об увлекательной жизни парня по имени Форест Гамп.\n' +
        'Маленький Форрест живет вместе со своей матерью в штате Алабама, в городке под названием Гринбоу. У него проблемы со здоровьем, да и ко всему прочему мальчик обладает расстройством интеллекта, поэтому его матери приходится приложить немало усилий, чтобы его взяли в обычную школу. В школе Форрест постоянно подвергается издевательствам со стороны сверстников, но это помогает ему научиться очень быстро бегать, что в будущем дает шанс парню стать студентом, и войти в число лучших спортсменов-любителей страны. После окончания университета Форрест идет в армию, и попадает на начавшуюся войну во Вьетнаме...',
    rating: 4.8,
  },
  {
    id: 14,
    nameEn: "Earth: One Amazing Day",
    nameRu: "Земля: Один потрясающий день",
    imgSm: "earth-one-amazing-day-min.jpg",
    imgLg: "earth-one-amazing-day-md.jpg",
    video: 'Земля_ Один потрясающий день — Русский трейлер (Дроздов 2018).mp4',
    duration: 95,
    year: 2017,
    type: "movie",
    director: 'Richard Deil',
    actors: ['Jackie Chan', 'Robert Redford'],
    category: ["family", "documentary"],
    aboutEn: 'The earth is home to a huge variety of organisms and animals. But what is one day in the life of these creatures? This captivating film takes you on an exciting journey that reveals the amazing power of the natural world. A zebra calf desperately trying to cross a river, a penguin heroically taking on a dangerous quest to feed his family, an incredible family of sperm whales, or a sloth searching for love - all these animals prove that every day is filled with unimaginable and inspiring wonders.\n',
    aboutRu: 'Земля является домом для огромного множества организмов и животных. Но что такое один день в жизни этих существ? Этот захватывающий фильм позволяет отправиться в увлекательное путешествие, раскрывающее удивительную силу природного мира. Детеныш зебры, отчаянно пытающийся пересечь реку, пингвин, который героически берет на себя опасную вылазку за пищей для своей семьи, невероятное семейство кашалотов или ленивец в поисках любви – все эти животные доказывают, что каждый день наполнен невообразимыми и вдохновляющими чудесами.',
    rating: 4.1,
  },
  {
    id: 15,
    nameEn: "Schindler's List",
    nameRu: "Список Шиндлера",
    imgSm: "schindlers-list-min.jpeg",
    imgLg: "schindlers-list-md.jpeg",
    video: 'Schindler\'s List (1993) Official Trailer - Liam Neeson, Steven Spielberg Movie HD.mp4',
    duration: 195,
    year: 1993,
    type: "movie",
    director: 'Steven Spielberg',
    actors: ['Liam Neeson','Ralph Fiennes','Ben Kingsley','Caroline Goodall','Jonathan Sagall','Embeth Davidtz'],
    category: ["drama"],
    aboutEn: 'The plot of the film is based on Thomas Keneally\'s novel "Schindler\'s Ark". The film tells about a German businessman who saved more than one thousand Polish Jews during World War II.\n' +
        'Arriving in occupied Poland, Oskar Schindler, having found a common language with the right people, receives permission to open a factory in Krakow for the production of enameled products. In order to find money to open a company and recruit workers, Schindler turns to the wealthy Jewish community and makes them a very lucrative offer: they give him money, and in return he gives them a variety of goods and jobs, which will give them a chance to leave the ghetto. Oskar makes a member of the Jewish council, Yitzhak Stern, the manager of the company. The established production begins to bring in large incomes. However, an order soon arrives for the extermination of Jews in the Auschwitz concentration camp...',
    aboutRu: 'В основу сюжета картины лег роман Томаса Кенилли «Ковчег Шиндлера». Картина рассказывает о немецком бизнесмене, спасшем во время Второй Мировой войны не одну тысячу польских евреев.\n' +
        'Прибыв на территорию оккупированной Польши, Оскар Шиндлер, найдя общий язык с нужными людьми, получает разрешение на открытие в Кракове фабрики по производству эмалированных изделий. Чтобы найти деньги на открытие предприятия и набрать рабочих, Шиндлер обращается к богатой еврейской общине, и делает им очень выгодное предложение: они ему деньги, а он им взамен разнообразные товары и рабочие места, что даст шанс покидать гетто. Управляющим на предприятии Оскар делает члена еврейского совета – Ицхаку Штерна. Налаженное производство начинает приносить большие доходы. Однако в скором времени приходит приказ об уничтожении евреев, находящихся в концлагере Аушвиц...',
    rating: 5,
  },
  {
    id: 16,
    nameEn: "The Godfather Trilogy: 1901-1980",
    nameRu: "Крестный отец: Трилогия 1901-1980",
    imgSm: "the-godfather-trilogy-min.jpg",
    imgLg: "the-godfather-trilogy-md.jpg",
    video: 'The Godfather Trilogy - The Coppola Restoration Trailer.mp4',
    duration: 583,
    year: 1992,
    type: "movie",
    director: 'Francis Ford Coppola',
    actors: ['Marlon Brando','Al Pacino','Robert Duvall','Robert De Niro','Diane Keaton','Talia Shire','James Caan'],
    category: ["drama", "thriller", "criminal"],
    aboutEn: 'The film is a saga about the rise and fall of the Corleone crime clan, spanning three generations of the Vito family, who emigrated from Italy to the United States of America after the murder of his father, his older brother and mother. Thanks to his strong character, yesterday\'s immigrant quickly became the head of a large group of Italian criminals in New York. The story is told chronologically, combining three previously released films, with the addition of a total of sixty minutes of scenes cut from previous films.',
    aboutRu: 'Фильм представляет собой сагу о взлёте и падении преступного клана Корлеоне, охватывающем три поколения семейства Вито, эмигрировавшего из Италии в Соединённые Штаты Америки после убийства отца, его старшего брата и матери. Благодаря твёрдому характеру вчерашний иммигрант достаточно быстро возглавил крупную группировку итальянских преступников в Нью-Йорке. История рассказывается в хронологическом порядке, объединяя три ранее выпущенные картины, с добавлением в общей сложности шестидесяти минут вырезанных из предыдущих фильмов сцен.',
    rating: 5,
  },
  {
    id: 17,
    nameEn: "Intouchables / The Intouchables",
    nameRu: "1+1",
    imgSm: "intouchables-min.jpeg",
    imgLg: "intouchables-md.jpeg",
    video: 'The Intouchables Official Trailer #1 (2012) HD Movie.mp4',
    duration: 112,
    year: 2011,
    type: "movie",
    director: 'Olivier Nakache',
    actors: ['François Cluzet','Omar Sy','Anne Le Ny','Audrey Fleurot','Clotilde Mollet','Alba Gaïa Bellugi'],
    category: ["drama", "comedy"],
    aboutEn: 'Philip is a very rich man, but as a result of an accident he was paralyzed and confined to a wheelchair. He has lost all interest in life, and needs constant supervision. Nurses are hired for these purposes, but none of them work for a long time.\n' +
        'And one day, Philip\'s next nurse becomes a black young guy named Drissa, who recently got out of prison. It is difficult to imagine such a person in the role of a nurse, but the guy manages to find a common language with Philip. He does not feel sorry for him, and treats him not as a disabled person, but as a healthy person. They have fun together, and thanks to this, Philip begins to look at life in a new way, and even falls in love.',
    aboutRu: 'Филипп очень богатый человек, но в результате несчастного случая его парализовало, и он прикован к инвалидному креслу. Он потерял всякий интерес к жизни, и нуждается в постоянном присмотре. Для этих целей нанимаются сиделки, однако ни одна из них долго не работает.\n' +
        'И вот однажды, очередной сиделкой Филиппа становится чернокожий молодой парень по имени Дрисса, вышедший совсем недавно из тюрьмы. Сложно представить такого человека в роли сиделки, однако парень умудряется найти общий язык с Филиппом. Он не жалеет его, и относится к нему не как к инвалиду, а как к здоровому человеку. Они весело проводят время вместе, и благодаря этому Филипп начинает смотреть на жизнь по-новому, и даже влюбляется.',
    rating: 4.8,
  },
  {
    id: 18,
    nameEn: "Inception",
    nameRu: "Начало",
    imgSm: "inception-min.jpeg",
    imgLg: "inception-md.jpeg",
    video: 'Начало (Inception) - Русский трейлер.mp4',
    duration: 148,
    year: 2010,
    type: "movie",
    director: 'Christopher Nolan',
    actors: ['Leonardo DiCaprio','Joseph Gordon-Levitt','Elliot Page','Ken Watanabe','Tom Hardy','Dileep Rao','Cillian Murphy'],
    category: ["action", "thriller", "drama"],
    aboutEn: 'We are used to the fact that in our understanding a thief is a person capable of stealing some valuables or money. The plot of the film tells about thieves who are able to steal an idea directly from a person from the subconscious. One of these is the main character of the film Dominic Cobb. After his wife died, he is forced into hiding, and cannot even return to the country to see his children. One day Cobb receives a very unusual order: he does not need to steal, but rather to introduce a new idea into the subconscious of a person. Dominic doesn\'t really want to take on this case, but the customer in exchange offers the opportunity to return home. With the support of professionals in this business, Cobb begins to develop a plan for how to pull it off. Everything needs to be thought out very well, because thieves will have to recreate a multi-layered reality in the subconscious of the object, as a result of which the edges may begin to fade.',
    aboutRu: 'Мы привыкли, что в нашем понимании вор – это человек способный украсть какие-то ценности или деньги. Сюжет картины рассказывает о ворах, способных украсть идею прямо у человека из подсознания. Одним из таких является главный герой фильма Доминик Кобб. После того, как его жена умерла, он вынужден скрываться, и не может даже вернуться в страну, чтобы повидать детей. Как-то раз Кобб получает очень неординарный заказ: ему нужно не украсть, а наоборот внедрить новую идею в подсознание человека. Доминику не очень хочется браться за это дело, но заказчик в обмен предлагает возможность вернуться домой. Заручившись поддержкой профессионалов этого дела, Кобб начинает разрабатывать план, как все провернуть. Все нужно очень хорошо продумать, ведь ворам предстоит воссоздать многослойную реальность в подсознании объекта, в результате чего грани могут начать стираться.',
    rating: 4.7,
  },
  {
    id: 19,
    nameEn: "Leon",
    nameRu: "Леон",
    imgSm: "leon-min.jpeg",
    imgLg: "leon-md.jpeg",
    video: 'Леон трейлер на русском.mp4',
    duration: 133,
    year: 1994,
    type: "movie",
    director: 'Luc Besson',
    actors: ['Jean Reno','Gary Oldman','Natalie Portman','Danny Aiello','Peter Appel','Willi One Blood'],
    category: ["thriller", "drama", "criminal"],
    aboutEn: 'Leon leads a quiet and peaceful lifestyle in one of the not the best areas of New York called Little Italy. No one can even imagine that this man is a real contract killer. One day, while at home, Leon hears a noise, and looking through the peephole of his door, he witnesses the whole family living in the next apartment being killed. Only a teenage girl, Matilda, who was not at home at the time, manages to survive. She turns to her neighbor Leon for help, because she has nowhere else to go. The cold-blooded killer suddenly begins to experience feelings alien to him before, and lets the girl in. They begin to live together, and after learning what her savior does for a living, Matilda asks to teach her how to kill so that she can take revenge on the murderers of her family. But it\'s unlikely to lead to anything good.…',
    aboutRu: 'Леон ведет тихий и спокойный образ жизни в одном из не самых лучших районов Нью-Йорка под названием Маленькая Италия. Никто даже представить себе не может, что этот человек самый настоящий наемный убийца. Однажды, находясь дома, Леон слышит шум, и, посмотрев в глазок своей двери, он становится свидетелем того, как всю семью, живущую в соседней квартире, убивают. Выжить удается только девочке-подростку Матильде, которой в то время не было дома. Она обращается к своему соседу Леону за помощью, ведь ей больше некуда идти. Хладнокровный убийца вдруг начинает испытывать чуждые ранее ему чувства, и пускает девочку к себе. Они начинают жить вместе, и узнав чем ее спаситель зарабатывает на жизнь, Матильда просит научить ее убивать, чтобы она могла отомстить убийцам своей семьи. Но вряд ли это приведет к чему-нибудь хорошему…',
    rating: 4.7,
  },
  {
    id: 20,
    nameEn: "Interstellar",
    nameRu: "Интерстеллар",
    imgSm: "interstellar-min.jpeg",
    imgLg: "interstellar-md.jpeg",
    video: 'Интерстеллар (Interstellar) -- дублированный трейлер.mp4',
    duration: 169,
    year: 2014,
    type: "movie",
    director: 'Christopher Nolan',
    actors: ['Matthew McConaughey','Anne Hathaway','Jessica Chastain','Mackenzie Foy','Ellen Burstyn'],
    category: ["fantasy", "drama", "adventure"],
    aboutEn: 'In the future, climate change has led to a catastrophic decrease in yields and the extinction of the most common crops. The population suffers from hunger and disease on the sand-covered Land, and former pilot Cooper, like most Americans, had to give up his career to take up farming. One day, his daughter Murphy is scared by a ghost in her own bedroom, who left her a coded message. At first, the father does not believe the girl, but soon together they decode the code and, following the prompts, find a secret NASA base where scientists are creating a unique spacecraft capable of flying through a black hole and reaching a habitable planet capable of becoming a new home for all mankind...',
    aboutRu: 'В будущем климатические изменения привели к катастрофическому снижению урожайности и вымиранию самых распространенных сельскохозяйственных культур. Население страдает от голода и болезней на покрытой песком Земле, а бывший пилот Купер, как и большинство американцев, вынужден был бросить карьеру, чтобы заняться фермерством. Однажды его дочь Мёрфи пугается призрака в собственной спальне, оставившего ей закодированное сообщение. Сначала отец не верит девочке, но вскоре вместе они расшифровывают код и, следуя подсказкам, находят секретную базу НАСА, где ученые занимаются созданием уникального космического корабля, способного пролететь через черную дыру и достичь пригодной для обитания планеты, способной стать новым домом для всего человечества...',
    rating: 4.7,
  },
  {
    id: 21,
    nameEn: "Das Beste kommt noch!",
    nameRu: "Достучаться до небес 2",
    imgSm: "das-beste-kommt-noch-min.jpg",
    imgLg: "das-beste-kommt-noch-md.jpg",
    video: 'Das Beste kommt noch! I Offizieller Trailer.mp4',
    duration: 111,
    year: 2023,
    type: "movie",
    director: 'Til Schweiger',
    actors: ['Til Schweiger','Michael Maertens','Neda Rahmanian','Franziska Machens','Emma Schweiger','Caro Cult'],
    category: ["comedy"],
    aboutEn: 'Mistakenly deciding that they are both about to be overtaken by a fatal illness, the friends rush to fulfill all their cherished desires. To do this, they will need someone else\'s car, a double-humped camel, a bottle of the most expensive champagne and the love of beautiful women to whom they have been going to confess something all their lives, but somehow they did not have enough time.',
    aboutRu: 'Ошибочно решив, что их обоих вот-вот настигнет смертельная болезнь, друзья бросаются напоследок исполнить все свои заветные желания. Для этого им потребуется чужая тачка, двугорбый верблюд, бутылка самого дорогого шампанского и любовь прекрасных женщин, которым они всю жизнь собирались в чем-то признаться, но все как-то не хватало времени.',
    rating: 3.9,
  },
  {
    id: 22,
    nameEn: "Lock, Stock and Two Smoking Barrels",
    nameRu: "Карты, деньги, два ствола",
    imgSm: "lock-stock-and-two-smoking-barrels-min.jpeg",
    imgLg: "lock-stock-and-two-smoking-barrels-md.jpeg",
    video: 'Карты деньги два ствола (1998) - трейлер фильма.mp4',
    duration: 107,
    year: 1998,
    type: "movie",
    director: 'Guy Ritchie',
    actors: ['Jason Flemyng','Dexter Fletcher','Nick Moran','Jason Statham','Steven Mackintosh','Nicholas Rowe'],
    category: ["thriller", "comedy", "criminal", "action"],
    aboutEn: 'The film is set in London. In the center of the plot of the picture are four bosom friends – Eddie, Tom, "Bacon" and "Soap", who earn their living by various kinds of adventures. One day, each of them collects a tidy sum of money, in the amount of 25 thousand pounds, so that Eddie can take part in a card game, because if he wins, the guys will hit a good jackpot. The organization of the game is occupied by a criminal authority named Harry Lonsdale. The guys somehow did not take into account that Harry is an excellent card cheat, and therefore the game will be clearly unfair. As a result, Eddie not only lost the money collected by his friends, but also ended up owing the bandit half a million, after which he received a one-week deadline to repay the debt. This is where the incredible adventures of the four begin…',
    aboutRu: 'Действие фильма разворачивается в Лондоне. В центре сюжета картины четверо закадычных друзей – Эдди, Том, «Бекон» и «Мыло», зарабатывающие себе на жизнь различного рода авантюрами. Однажды каждый из них собирает кругленькую сумму денег, в размере 25 тысяч фунтов, чтобы Эдди смог принять участие в карточной игре, ведь если он победит, то парни сорвут неплохой куш. Организацией игры занимает криминальный авторитет по имени Гарри Лонсдейл. Парни как-то не учли, что Гарри отменный карточный жулик, и поэтому игра будет явно нечестной. В результате Эдди мало того, что проиграл собранные друзьями деньги, так еще и оказался должен бандиту пол миллиона, после чего получил недельный срок на возвращение долга. Тут и начинаются невероятные приключения четверки…',
    rating: 4.5,
  },
  {
    id: 23,
    nameEn: "Roger Waters the Wall",
    nameRu: "Роджер Уотерс: The Wall",
    imgSm: "roger-waters-the-wall-min.jpg",
    imgLg: "roger-waters-the-wall-md.jpg",
    video: 'Roger Waters The Wall Official Trailer 1 (2015) - Documetary HD.mp4',
    duration: 132,
    year: 2014,
    type: "movie",
    director: 'Sean Evans',
    actors: ['Roger Waters','Dave Kilminster','Snowy White','G.E. Smith','Harry Waters','Graham Broad'],
    category: ["documentary"],
    aboutEn: 'In 1979, Pink Floyd released its eleventh album, entitled "The Wall", which leads all world charts and brings stunning commercial success. More than thirty years later, the band\'s frontman Roger Waters, together with director Sean Evans, is working on the production of a concert film, where, thanks to enchanting computer effects and expensive decorations, he recreates a musical show on stage, where he pleases fans with compositions from the legendary album in a live performance.',
    aboutRu: 'В 1979-ом году Pink Floyd выпускает свой одиннадцатый альбом под названием «The Wall», который лидирует во всех мировых чартах и приносит ошеломительный коммерческий успех. Более тридцати лет спустя фронтмен группы Роджер Уотерс совместно с режиссером Шоном Эвансом работает над производством концертного фильма, где благодаря феерическим компьютерным эффектам и дорогим декорациям воссоздает на сцене музыкальное шоу, где в живом исполнении радует поклонников композициями из легендарного альбома.',
    rating: 4.5,
  },
  {
    id: 24,
    nameEn: "A Beautiful Mind",
    nameRu: "Игры разума",
    imgSm: "a-beautiful-mind-min.jpeg",
    imgLg: "a-beautiful-mind-md.jpeg",
    video: 'A Beautiful Mind (2001) Theatrical Trailer.mp4',
    duration: 135,
    year: 2001,
    type: "movie",
    director: 'Ron Howard',
    actors: ['Russell Crowe','Ed Harris','Jennifer Connelly','Christopher Plummer','Adam Goldberg'],
    category: ["drama"],
    aboutEn: 'The biographical drama "Mind Games" is based on the book of the same name by Sylvia Nazar. The picture tells about the life of an outstanding mathematician who made a huge contribution to the development of exact sciences. In 1947, thanks to his mathematical talent, John Nash entered Princeton University. He leads a secluded lifestyle, practically does not communicate with anyone except his roommate Jim and his niece Marcie. Nash is immersed in research. After graduating with honors, John goes to teach at the Massachusetts Institute of Technology, where he meets his future wife. One day, the CIA comes out to Nash in the person of Agent Parcher. He is asked to analyze information published in open sources in order to identify correspondence between enemies of the United States. He takes the job, but soon refuses...',
    aboutRu: 'Биографическая драма «Игры разума» снята по мотивам одноименной книги Сильвии Назар. Картина повествует о жизни выдающегося математика, внесшего огромный вклад в развитие точных наук. В 1947 году, благодаря своему математическому таланту, Джон Нэш поступает в Принстонский университет. Он ведет уединенный образ жизни, практически ни с кем не общается, кроме своего соседа по комнате Джима и его племянницы Марси. Нэш уходит с головой в исследования. Закончив с отличием учебу, Джон идет преподавать в Массачусетский технологический университет, где знакомится со своей будущей женой. Однажды на Нэша выходит ЦРУ в лице агента Парчера. Его просят анализировать опубликованную в открытых источниках информацию, с целью выявления переписок врагов США. Он берется за эту работу, однако в скором времени отказывается...',
    rating: 4.4,
  },
  {
    id: 25,
    nameEn: "Beware of hooligans",
    nameRu: "Берегите хулиганов",
    imgSm: "beware-of-hooligans-min.jpg",
    imgLg: "beware-of-hooligans-md.jpg",
    video: 'Берегите хулиганов _ Трейлер (2021) more.tv.mp4',
    duration: 63,
    year: 2021,
    type: "movie",
    director: 'Иван Проскуряков',
    actors: [],
    category: ["documentary"],
    aboutEn: 'The film tells about the only circus in the world where difficult teenagers learn circus art and become real artists. By its example, the Uppsala Circus project shows how, with the help of creativity, children can be given the opportunity to live a more interesting and successful life. History makes it clear to teenagers that there are places where they will be welcome, and people who are ready to understand and help.',
    aboutRu: 'Фильм рассказывает о единственном в мире цирке, где трудные подростки обучаются цирковому искусству и становятся настоящими артистами. На своем примере проект «‎Упсала-Цирк» показывает, как при помощи творчества можно подарить детям возможность прожить более интересную и успешную жизнь. История дает понять подросткам, что есть и места, где им будут рады, и люди, готовые понять и помочь.',
    rating: 4.4,
  },
  {
    id: 26,
    nameEn: "The Godfather: Part II",
    nameRu: "Крестный отец 2",
    imgSm: "the-godfather-2-min.jpeg",
    imgLg: "the-godfather-2-md.jpeg",
    video: 'The Godfather Part II - Trailer.mp4',
    duration: 202,
    year: 1974,
    type: "movie",
    director: 'Francis Ford Coppola',
    actors: ['Al Pacino','Robert De Niro','Robert Duvall','Diane Keaton','John Cazale'],
    category: ["drama", "thriller", "criminal"],
    aboutEn: 'For Don Corleone and his son, there are no moral barriers to achieving their goals. They turn the mafia, built according to patriarchal Sicilian laws, into a very pragmatic, rigid corporation, smoothly integrating it into the big business of America.',
    aboutRu: 'Для дона Корлеоне и его сына не существует моральных преград на пути к достижению целей. Они превращают мафию, построенную по патриархальным сицилийским законам, в весьма прагматичную, жесткую корпорацию, плавно интегрируя её в большой бизнес Америки.',
    rating: 5,
  },
  {
    id: 27,
    nameEn: "The Dark Knight",
    nameRu: "Темный рыцарь",
    imgSm: "the-dark-knight-min.jpg",
    imgLg: "the-dark-knight-md.jpg",
    video: 'Фильм Темный рыцарь (русский трейлер 2008).mp4',
    duration: 152,
    year: 2008,
    type: "movie",
    director: 'Christopher Nolan',
    actors: ['Christian Bale','Heath Ledger','Aaron Eckhart','Michael Caine','Maggie Gyllenhaal','Gary Oldman'],
    category: ["action", "thriller", "criminal", "fantasy"],
    aboutEn: 'The hero of the film Bruce Wayne, aka Batman, is going to end his secret life, realizing that the city does not really need a "Dark Knight" on the other side of the law, but a real, obvious hero, who, in his opinion, can become an unshakeable, and eager to crack down on crime prosecutor Harvey Dent. At this time, another threat looms over Gotham in the person of a criminal nicknamed the Joker. The lives of Wayne and Dent are changing dramatically, because the new enemy is very cunning and smart, and is able to let out the dark inside of both heroes.',
    aboutRu: 'Герой фильма Брюс Уэйн, он же Бэтмен, собирается покончить с тайной жизнью, понимая, что город на самом деле нуждается не в «Темном рыцаре», находящемся по ту сторону закона, а в настоящем, явном герое, которым, по его мнению, может стать непоколебимый, и жаждущий расправы с преступностью прокурор Харви Дент. В это время над Готэмом нависает очередная угроза в лице преступника по прозвищу Джокер. Жизнь Уэйна и Дента меняется кардинальным образом, ведь новый враг очень хитер и умен, и способен выпустить наружу темное нутро обоих героев.',
    rating: 5,
  },
  {
    id: 28,
    nameEn: "Shutter Island",
    nameRu: "Остров проклятых",
    imgSm: "shutter-island-min.jpeg",
    imgLg: "shutter-island-md.jpeg",
    video: 'Остров проклятых (2010) — русский трейлер.mp4',
    duration: 138,
    year: 2010,
    type: "movie",
    director: 'Martin Scorsese',
    actors: ['Leonardo DiCaprio', 'Emily Mortimer','Mark Ruffalo','Ben Kingsley','Max von Sydow'],
    category: ["thriller", "drama"],
    aboutEn: 'The film is set in 1954 in the USA. Federal Marshal Teddy Daniels, along with his partner Chuck Oul, goes to the closed island of Shatter to investigate the escape that took place there. There is a secret and well-guarded clinic on the island, where the most violent and unpredictable mentally ill are imprisoned. One of them, namely Rachel Solando, the murderer of her own children, somehow miraculously managed to escape directly from a closed ward. The federal marshal is trying to figure out how she did it, but he is very hampered by incomprehensible dreams. And then there\'s a strong hurricane, completely cut off from the mainland. But for now, Marshal Daniels can\'t even imagine that even more serious challenges lie ahead.',
    aboutRu: 'Действие картины разворачивается в 1954 году в США. Федеральный маршал Тедди Дениелс вместе со своим напарником Чаком Оулом отправляется на закрытый остров Шаттер, для расследования произошедшего там побега. На территории острова находится засекреченная и хорошо охраняемая клиника, в которой отбывают заключение самые буйные и непредсказуемые душевнобольные. Одному из них, а именно Рэйчел Соландо – убийце родных детей, каким-то удивительным образом удалось сбежать прямо из закрытой палаты. Федеральный маршал пытается выяснить, как ей это удалось, однако ему очень мешают непонятные сновидения. А тут еще и сильный ураган, полностью отрезавший от большой земли. Но пока маршал Дениелс и представить себе не может, что впереди его ждут еще более серьезные испытания.',
    rating: 5,
  },
  {
    id: 28,
    nameEn: "The Departed",
    nameRu: "Отступники",
    imgSm: "the-departed-min.jpg",
    imgLg: "the-departed-md.jpg",
    video: '_Отступники_ трейлер русский дублированный 2006.mp4',
    duration: 151,
    year: 2006,
    type: "movie",
    director: 'Martin Scorsese',
    actors: ['Leonardo DiCaprio','Matt Damon','Jack Nicholson','Mark Wahlberg','Martin Sheen'],
    category: ["thriller", "criminal"],
    aboutEn: 'The plot of the film centers on two policemen, one of whom Colin Sullivan works for the mafia, and the other Billy Costigan was infiltrated into the ranks of the mafia group to identify the mole.\n' +
        'Once upon a time, they both graduated from the police academy, and were the best graduates, but the fate of the villain decreed that now the guys are on opposite sides of the barricades. Billy had to serve a real term to infiltrate the mafia, and now he is doing everything to identify the snitch, but so far in vain. At this time, it is Sullivan who is leading the official search for the mole, who needs to deflect all suspicion from himself...',
    aboutRu: 'В центре сюжета картины двое полицейских, один из которых Колин Салливан работает на мафию, а второй Билли Костиган был внедрен в ряды мафиозной группировки, чтобы выявить крота.\n' +
        'Когда-то давно они оба окончили полицейскую академию, и были лучшими выпускниками, однако судьба злодейка распорядилась так, что теперь парни по разные стороны баррикад. Билли пришлось отсидеть реальный срок, чтобы внедриться в мафию, и теперь он делает все, чтобы выявить стукача, но пока тщетно. В это время официальное дело по поиску крота ведет именно Салливан, которому нужно отвести от себя все подозрения...',
    rating: 4.8,
  },
  {
    id: 29,
    nameEn: "White Bird",
    nameRu: "Белая птица: Новое чудо",
    imgSm: "white-bird-min.jpg",
    imgLg: "white-bird-md.jpg",
    video: 'Белая птица_ Новое чудо — Русский трейлер (2024).mp4',
    duration: 122,
    year: 2023,
    type: "movie",
    director: 'Marc Forster',
    actors: ['Gillian Anderson','Olivia Ross','Helen Mirren','Bryce Gheisar','Orlando Schwerdt','Patsy Ferran'],
    category: ["adventure", "drama", "family"],
    aboutEn: 'Teenager Julian, who regularly gets into various troubles, was recently expelled from school for bullying his classmate Auggie. The student is visited by his grandmother Sarah, a famous Jewish artist, who decides to tell him an instructive story from her childhood. The events take place during the Second World War, when she lived in Nazi-occupied France. Sarah risks going to a concentration camp, but unexpectedly finds shelter in the family of her classmate Julien Beaumier, a polio—stricken outcast whom she previously tried not to notice.',
    aboutRu: 'Подросток Джулиан, регулярно попадающий в различные неприятности, недавно был исключен из школы за издевательства над своим одноклассником Огги. Школьника навещает его бабушка Сара, знаменитая еврейская художница, которая решает рассказать ему поучительную историю из своего детства. События переносятся во времена Второй мировой войны, когда она проживала в оккупированной нацистами Франции. Сара рискует попасть в концентрационный лагерь, но неожиданно находит укрытие в семье своего одноклассника Жюльена Бомье — больного полиомиелитом изгоя, которого она раньше старалась не замечать.',
    rating: 4.8,
  },
  {
    id: 30,
    nameEn: "Scent of a woman",
    nameRu: "Запах женщины",
    imgSm: "scent-of-a-woman-min.jpg",
    imgLg: "scent-of-a-woman-md.jpg",
    video: 'Scent of a Woman Official Trailer #1 - Al Pacino Movie (1992) Movie HD.mp4',
    duration: 157,
    year: 1992,
    type: "movie",
    director: 'Martin Brest',
    actors: ['Al Pacino','Chris O\'Donnell','James Rebhorn','Gabrielle Anwar','Philip Seymour Hoffman'],
    category: ["drama"],
    aboutEn: 'A young guy named Charlie Sims, a student at a prestigious school, decides to work part-time for the holidays. He gets a job with a married couple to look after their blind relative while they are away. This man turns out to be a retired colonel who lost his eyesight as a result of an accident in the service. As soon as the colonel\'s family leaves the house, it turns out that he does not intend to spend the weekend on the veranda, but wants to go to New York, and have a good rest there, not denying himself anything. Charlie has no choice but to go with him. This journey will forever change the lives of these two completely different people...',
    aboutRu: 'Молодой парень по имени Чарли Симс, учащийся в престижной школе, решает подработать на праздники. Он устраивается к семейной паре присматривать за их слепым родственником, пока те будут отсутствовать. Этим человеком оказывается отставной полковник, потерявший зрение в результате несчастного случая на службе. Как только родные полковника покидают дом, выясняется, что он не намерен проводить выходные на веранде, а хочет отправиться в Нью-Йорк, и как следует там отдохнуть, ни в чем себе не отказывая. Чарли не остается ничего другого, как поехать с ним. Это путешествие навсегда изменит жизнь этих двух совершенно разных людей...',
    rating: 5,
  },
  {
    id: 31,
    nameEn: "The Shawshank Redemption",
    nameRu: "Побег из Шоушенка",
    imgSm: "the-shawshank-redemption-min.jpeg",
    imgLg: "the-shawshank-redemption-md.jpeg",
    video: 'Побег из Шоушенка трейлер на русском.mp4',
    duration: 142,
    year: 1994,
    type: "movie",
    director: 'Frank Darabont',
    actors: ['Tim Robbins','Morgan Freeman','Bob Gunton','William Sadler','Clancy Brown'],
    category: ["drama", "criminal"],
    aboutEn: 'The cult drama is based on Stephen King\'s novel "Rita Hayworth from Shawshank". The film is set in the late 50s of the last century. Young financier Andy Dufresne is sentenced to life in prison for double murder, but he categorically denies any involvement in the crime. Andy goes to serve his sentence in one of the most famous prisons – Shawshank, from which no one has ever managed to escape. In prison, the guy is faced with the harsh realities of the prison world, a world where there is no place for compassion, and there is only cruelty around. Andy repeatedly becomes a victim of sexual harassment, but he resists to the last. Soon, Dufresne\'s prison life improves a little, and he even finds a friend, who becomes a black prisoner, Red...',
    aboutRu: 'В основу культовой драмы легла повесть Стивена Кинга «Рита Хейуорт из Шоушенка». Действие фильма разворачивается в конце 50-х годов прошлого столетия. Молодого финансиста Энди Дюфрейна за двойное убийство приговаривают к пожизненному заключению, но он категорически отрицает свою причастность к преступлению. Свой срок Энди отправляется отбывать в одну из известнейших тюрем – Шоушенк, из которой еще никому не удавалось сбежать. В тюрьме парень сталкивается с суровыми реалиями тюремного мира, мира, где нет места состраданию, а вокруг только жестокость. Энди неоднократно становится жертвой сексуальных домогательств, но он сопротивляется до последнего. В скором времени тюремная жизнь Дюфрейна немного налаживается, и он даже находит себе друга, которым становится чернокожий заключенный Рэд...',
    rating: 4.9,
  },
  {
    id: 32,
    nameEn: "HACHIKO",
    nameRu: "Мой Хатико",
    imgSm: "hachiko-min.jpg",
    imgLg: "hachiko-md.jpg",
    video: 'Мой Хатико _ My Hachiko (2023) _ ТРЕЙЛЕР.mp4',
    duration: 125,
    year: 2023,
    type: "movie",
    director: 'Ang Xu',
    actors: ['Jugang Bai','Joan Chen','Xiaogang Feng','Eponine Huang'],
    category: ["drama", "family"],
    aboutEn: 'One day in the early 2000s, an elderly associate professor of the Faculty of Engineering, Chen Jingxiu, who lives in Chongqing, goes on a work trip with colleagues to the countryside, where he picks up a stray Akita Inu puppy on the road, which he brings home and gives the nickname Hachiko. The man\'s wife Li Jiazhen, who has a pathological dislike for dogs, makes a scandal, but soon allows the puppy to stay and take the place of a full-fledged family member. Years later, Hachiko becomes a symbol of devotion and loyalty to her master.',
    aboutRu: 'Однажды в начале 2000-х годов пожилой доцент инженерного факультета Чэнь Цзинсю, проживающий в городе Чунцин, отправляется с коллегами в рабочую поездку в сельскую местность, где подбирает на дороге бездомного щенка породы акита-ину, которого приносит домой и дает кличку Хатико. Жена мужчины Ли Цзячжэнь, испытывающая патологическую неприязнь к собакам, устраивает скандал, но вскоре позволяет щенку остаться и занять место полноценного члена семьи. Годы спустя Хатико становится символом преданности и верности своему хозяину.',
    rating: 4.7,
  },
  {
    id: 33,
    nameEn: "Oppenheimer",
    nameRu: "Оппенгеймер",
    imgSm: "oppenheimer-min.jpg",
    imgLg: "oppenheimer-md.jpg",
    video: 'Oppenheimer _ New Trailer.mp4',
    duration: 180,
    year: 2023,
    type: "movie",
    director: 'Christopher Nolan',
    actors: ['Cillian Murphy','Emily Blunt','Matt Damon','Robert Downey Jr.','Alden Ehrenreich'],
    category: ["drama", "historical"],
    aboutEn: 'In the midst of World War II, U.S. Colonel Leslie Groves appoints the brilliant theoretical physicist Robert Oppenheimer as the scientific director of the Manhattan Project. All the industrial power and innovative technologies of the country are going to get ahead of Nazi Germany in creating weapons of mass destruction based on the splitting of the atomic nucleus. Oppenheimer successfully tests the world\'s first nuclear bomb, which makes it possible to bring victory in the war closer. Nevertheless, the man is tormented by remorse, because his invention can lead to the destruction of all mankind.',
    aboutRu: 'В разгар Второй мировой войны полковник США Лесли Гровс назначает блестящего физика-теоретика Роберта Оппенгеймера научным руководителем Манхэттенского проекта. Вся индустриальная мощь и инновационные технологии страны идут на то, чтобы опередить нацистскую Германию в создании оружия массового поражения на основе расщепления ядра атома. Оппенгеймер проводит успешные испытания первой в мире ядерной бомбы, что позволяет приблизить победу в войне. Тем не менее мужчину терзают угрызения совести, поскольку его изобретение способно привести к уничтожению всего человечества.',
    rating: 4.7,
  },
  {
    id: 34,
    nameEn: "Hockey Dads",
    nameRu: "Хоккейные папы",
    imgSm: "hokkeinie-papi-min.jpg",
    imgLg: "hokkeinie-papi-md.jpg",
    video: 'Хоккейные папы _ Трейлер.mp4',
    duration: 131,
    year: 2023,
    type: "movie",
    director: 'Андрей Булатов',
    actors: ['Ksenia Alekseeva','Grant Amiryan','Aleksandr Astashenok','Mark Badaev'],
    category: ["sports", "family"],
    aboutEn: 'Andrey is the coach of a children\'s hockey team in a small provincial town. The measured life of the hero is disrupted by the news that the only ice palace in the city, where he trains children, is going to be demolished. The only way to save him is to win an amateur hockey tournament. Andrey has only a few months to assemble the team and prepare it for the games. The fathers of young hockey players decide to go out on the ice themselves and fight for the future of their children.',
    aboutRu: 'Андрей — тренер детской хоккейной команды маленького провинциального городка. Размеренную жизнь героя нарушает известие о том, что единственный в городе ледовый дворец, где он тренирует детей, собираются снести. Единственная возможность его спасти — победить в любительском турнире по хоккею. У Андрея есть всего несколько месяцев для того, чтобы собрать команду и подготовить её к играм. Отцы маленьких хоккеистов решают сами выйти на лед и побороться за будущее своих детей.',
    rating: 4.4,
  },
  {
    id: 35,
    nameEn: "STILL: A Michael J. Fox Movie",
    nameRu: "Неизменный: Майкл Дж. Фокс",
    imgSm: "still-a-michael-jfox-min.jpg",
    imgLg: "still-a-michael-jfox-md.jpg",
    video: 'STILL_ A Michael J. Fox Movie — Official Trailer _ Apple TV .mp4',
    duration: 95,
    year: 2023,
    type: "movie",
    director: 'Davis Guggenheim',
    actors: ['Michael J. Fox','Davis Guggenheim','Tracy Pollan','Sam Fox'],
    category: ["documentary"],
    aboutEn: 'A documentary about the life of American actor Michael J. Fox. As a small child who grew up on a Canadian military base, Michael begins his own path to success as a talented actor who gains worldwide popularity in the 1980s when he gets the lead role in the trilogy "Back to the Future". Against the background of stunning success in his professional career, Michael J. Fox begins to experience some health problems, after which in 1990 he was diagnosed with a disappointing diagnosis — Parkinson\'s disease. From this moment on, the habitual life of a successful actor begins to change dramatically…',
    aboutRu: 'Документальный фильм о жизненном пути американского актера Майкла Джей Фокса. Будучи низкорослым ребенком, выросшим на канадской военной базе, Майкл начинает собственный путь к успеху в качестве талантливого актера, который обретает мировую популярность в 1980-х годах, когда он получает главную роль в трилогии «Назад в будущее». На фоне ошеломительного успеха в профессиональной деятельности Майкл Джей Фокс начинает испытывать некоторые проблемы со здоровьем, после чего в 1990 году ему ставят неутешительный диагноз — болезнь Паркинсона. С этого момента привычная жизнь успешного актера начинает кардинально меняться…',
    rating: 4.2,
  },
  {
    id: 36,
    nameEn: "Doctor",
    nameRu: "Доктор",
    imgSm: "doctor-min.jpg",
    imgLg: "doctor-md.jpg",
    video: 'Доктор - Русский трейлер (2023).mp4',
    duration: 120,
    year: 2023,
    type: "movie",
    director: 'Артём Темников',
    actors: ['Olga Cirsen','Sergei Puskepalis','Igor Chernevich','Denis Loginov'],
    category: ["drama"],
    aboutEn: 'At night, a terrible event occurs in the psycho-neurological department for teenagers — one of the patients almost dies. Adults assume that the culprit of the night\'s incident is one of the guys. Doctors fear that history will repeat itself and end in tragedy. There is a version that teenagers play "dog buzz" at night, a game with strangulation. Ivan Khristoforov, a talented psychiatrist who treats his young patients not so much with pills as with pedagogical methods, must figure everything out and stop the deadly game. But it turns out that finding the culprit is the easiest thing. It is much more difficult to save his soul — this becomes the main goal of Khristoforov. He is ready to sacrifice everything for this.',
    aboutRu: 'Ночью в психо-неврологическом отделении для подростков происходит ужасное событие — едва не гибнет один из пациентов. Взрослые предполагают, что виновник ночного происшествия — кто-то из ребят. Врачи опасаются, что история повторится и закончится трагедией. Есть версия, что подростки по ночам играют в «собачий кайф», игру с удушением. Разобраться во всем и остановить смертельную игру должен Иван Христофоров — талантливый психиатр, который лечит своих юных пациентов не столько таблетками, сколько педагогическими методами. Но, оказывается, что найти виновника — это самое простое. Гораздо сложнее спасти его душу — это и становится главной целью Христофорова. Ради этого он готов пожертвовать всем.',
    rating: 3.8,
  },
  {
    id: 37,
    nameEn: "Sound of Freedom",
    nameRu: "Звук свободы",
    imgSm: "sound-of-freedom-min.jpg",
    imgLg: "sound-of-freedom-md.jpg",
    video: 'Sound of Freedom - Official Trailer (2023).mp4',
    duration: 131,
    year: 2023,
    type: "movie",
    director: 'Alejandro Monteverde',
    actors: ['Jim Caviezel','Mira Sorvino','Bill Camp','Cristal Aparicio'],
    category: ["drama", "thriller", "action", "historical"],
    aboutEn: 'Tim is a federal agent for the Department of Homeland Security who works on cases involving child trafficking for sexual exploitation. During one mission, the agent manages to rescue Miguel, a boy from Honduras who became a victim of criminals along with his sister Rocio. After finding out the details about the disappearance of Miguel\'s sister, Tim decides to go to Colombia to track down the girl and free her from sexual slavery. Once in a deadly environment, the main character is determined not only to save Russia, but also to destroy the activities of a criminal organization engaged in child trafficking.',
    aboutRu: 'Тим — федеральный агент Министерства внутренней безопасности, который работает над делами, связанными с торговлей детьми в целях сексуальной эксплуатации. Во время одной миссии агенту удается спасти Мигеля, мальчика из Гондураса, ставшего жертвой преступников вместе со своей сестрой Росио. Выяснив подробности об исчезновении сестры Мигеля, Тим принимает решение отправиться в Колумбию, чтобы выйти на след девушки и освободить ее из сексуального рабства. Оказавшись в смертельно опасной среде, главный герой полон решимости не только спасти Росио, но и разрушить деятельность преступной организации, занимающейся торговлей детьми.',
    rating: 4.1,
  },
  {
    id: 38,
    nameEn: "Poor Things",
    nameRu: "Бедные-несчастные",
    imgSm: "poor-things-min.jpg",
    imgLg: "poor-things-md.jpg",
    video: 'POOR THINGS _ Official Trailer _ Searchlight UK.mp4',
    duration: 141,
    year: 2023,
    type: "movie",
    director: 'Yorgos Lanthimos',
    actors: ['Emma Stone','Mark Ruffalo','Willem Dafoe','Ramy Youssef','Vicki Pepperdine'],
    category: ["drama", "fantasy", "comedy", "artHouse"],
    aboutEn: 'In Victorian London, a young pregnant woman commits suicide by jumping from a high bridge into the Thames. Brilliant but slightly crazy scientist Godwin Baxter resuscitates a woman by transplanting the brain of her unborn baby so that she does not remember her past life, in which she was unhappy. This is how the story of Bella Baxter begins, who looks at the world through the eyes of a child, being completely free from the prejudices of her time. One day, she runs away from home with lawyer Duncan Wedderburn, trying to get to know the world around her and herself.',
    aboutRu: 'В викторианском Лондоне молодая беременная женщина кончает жизнь самоубийством, прыгнув с высокого моста в Темзу. Блестящий, но слегка сумасшедший ученый Годвин Бакстер реанимирует женщину, пересадив ей мозг ее нерожденного младенца, чтобы она не помнила свою прошлую жизнь, в которой была несчастна. Так начинается история Беллы Бакстер, которая смотрит на мир глазами ребенка, будучи абсолютно свободной от предрассудков своего времени. Однажды она сбегает из дома с адвокатом Дунканом Веддерберном, пытаясь познать окружающий мир и себя.',
    rating: 4.4,
  },
];
