import {I_SeriesApi} from "../../models/server/films/interfaces.ts";

export const allSeriesApi: I_SeriesApi[] = [
    {
        id: 0,
        nameEn: 'Dead Boy Detectives',
        nameRu: 'Детективы с того света',
        imgSm: 'dead-boy-detectives-min.jpg',
        imgLg: 'dead-boy-detectives-md.jpg',
        video: 'Детективы с того света (1 сезон) — Русский трейлер (Субтитры 2024).mp4',
        duration: 54,
        year: 2024,
        type: 'series',
        director: 'Steve Yockey',
        actors: ['Jayden Revri','George Rexstrew','Kassius Nelson','Briana Cuoco'],
        category: ['fantasy','adventure','action','drama','comedy','thriller','horror'],
        aboutEn: 'Edwin Payne has been dead for more than a century, and during this period he managed to serve his own time in hell. Charles Rowland was tortured to death in 1990 at the same boarding school that Payne attended. Having become best friends, Edwin and Charles have personal reasons not to go into the afterlife, although Death itself comes to look for them both from time to time. Successfully avoiding unwanted encounters with Death, the friends remain in the world of the living as ghosts and investigate criminal crimes related to the supernatural.',
        aboutRu: 'Эдвин Пейн мертв уже более века, и за этот период он успел отсидеть собственный срок в аду. Чарльз Роуленд был замучен до смерти в 1990 году в той же школе-интернате, которую посещал Пейн. Став лучшими друзьями, Эдвин и Чарльз имеют личные причины не переходить в загробную жизнь, хотя сама Смерть время от времени приходит искать их обоих. Успешно избегая нежелательных встреч со Смертью, приятели остаются в мире живых в качестве призраков и занимаются расследованиями криминальных преступлений, связанных со сверхъестественным.',
        rating: 4.8
    },
    {
        id: 1,
        nameEn: 'The Sympathizer',
        nameRu: 'Сочувствующий',
        imgSm: 'the-sympathizer-min.jpg',
        imgLg: 'the-sympathizer-md.jpg',
        video: 'The Sympathizer _ Official Trailer _ Max.mp4',
        duration: 50,
        year: 2024,
        type: 'series',
        director: 'Don McKellar',
        actors: ['Hoa Xuande','Toan Le','Fred Nguyen Khan','Tom Dang','Tien Pham'],
        category: ['comedy','drama','thriller'],
        aboutEn: 'Towards the end of the Vietnam War, the double agent Captain flees the captured region to the United States. He continues to spy for the Communists of North Vietnam, and is also a trusted CIA official and provides American intelligence with information about his leader\'s plans. In Los Angeles, the main character is forced to settle in a special refugee community, continuing to risk his life in spy games. Performing various, sometimes absurd tasks, the Captain tries to remain faithful to his true employer, not to lose himself in the American dream and fight a desperate longing for his native home.',
        aboutRu: 'Ближе к концу войны во Вьетнаме двойной агент Капитан бежит из захваченного региона в США. Он продолжает шпионить в пользу коммунистов Северного Вьетнама, а также является доверенным лицом ЦРУ и предоставляет американской разведке информацию о планах своего руководителя. В Лос-Анджелесе главный герой вынужден поселиться в специальной общине для беженцев, продолжая рисковать жизнью в шпионских играх. Выполняя различные, иногда абсурдные задания, Капитан пытается сохранить верность своему истинному работодателю, не потерять себя в американской мечте и бороться с отчаянной тоской по родному дому.',
        rating: 4.1
    },
    {
        id: 2,
        nameEn: 'Franklin',
        nameRu: 'Франклин',
        imgSm: 'franklin-min.jpg',
        imgLg: 'franklin-md.jpg',
        video: 'Franklin — Official Trailer _ Apple TV .mp4',
        duration: 55,
        year: 2024,
        type: 'series',
        director: 'Michael Douglas',
        actors: ['Michael Douglas','Noah Jupe','Daniel Mays','Ludivine Sagnier'],
        category: ['drama'],
        aboutEn: 'About the American statesman Benjamin Franklin, an outstanding polymath of the XVIII century.',
        aboutRu: 'Об американском государственном деятеле Бенджамине Франклине, выдающемся полимате XVIII века.',
        rating: 4.8
    },
    {
        id: 3,
        nameEn: 'Fallout',
        nameRu: 'Фоллаут',
        imgSm: 'fallout-min.jpg',
        imgLg: 'fallout-md.jpg',
        video: 'Fallout - Official Trailer _ Prime Video.mp4',
        duration: 60,
        year: 2024,
        type: 'series',
        director: 'Geneva Robertson-Dworet',
        actors: ['Ella Purnell','Aaron Moten','Walton Goggins','Moises Arias'],
        category: ['fantasy','adventure','action','drama'],
        aboutEn: 'The events unfold in the world of retrofuturism, where the transistor was not invented, and all technologies are based on nuclear energy. On October 23, 2077, the Great War between the superpowers took place, which put an end to the former human civilization. More than two hundred years later, a young woman, Lucy McLean, who was born and grew up in a comfortable underground shelter, as a result of circumstances comes to the surface, where she encounters gangs of raiders, carnivorous mutants and other dangers of post-apocalyptic Los Angeles. Soon, two new friends become her companions — a Steel Brotherhood squire named Maximus and the once-popular Hollywood actor Cooper Howard, who mutated into a ghoul and retrained into a bounty hunter.',
        aboutRu: 'События разворачиваются в мире ретрофутуризма, где не был изобретен транзистор, а все технологии построены на ядерной энергетике. 23 октября 2077 года произошла Великая война между сверхдержавами, которая положила конец прежней человеческой цивилизации. Более двухсот лет спустя молодая женщина Люси Маклин, родившаяся и выросшая в комфортном подземном убежище, в результате обстоятельств выходит на поверхность, где сталкивается с бандами рейдеров, плотоядными мутантами и прочими опасностями постапокалиптического Лос-Анджелеса. Вскоре её спутниками становятся двое новых друзей — оруженосец Братства Стали по имени Максимус и некогда популярный голливудский актер Купер Хауард, который мутировал в гуля и переквалифицировался в охотника за головами.',
        rating: 4.9
    },
    {
        id: 4,
        nameEn: 'Gisaengsu: Deo Geurei / Parasyte: The Grey',
        nameRu: 'Паразит: Серые',
        imgSm: 'gisaengsu-deo-geurei-min.jpg',
        imgLg: 'gisaengsu-deo-geurei-md.jpg',
        video: 'Паразит_ Серый (2024) _ Официальный трейлер _ Нетфликс.mp4',
        duration: 50,
        year: 2024,
        type: 'series',
        director: 'Jeon So-nee',
        actors: ['Jeon So-nee','Koo Kyo-hwan','Lee Jung-hyun','Kwon Hae-hyo','Kim In-kwon'],
        category: ['fantasy','horror','action','thriller'],
        aboutEn: 'Parasite creatures that have arrived on Earth from the depths of space are gradually beginning to penetrate into people\'s bodies, taking them under control in order to subjugate the whole of humanity in the future. One of the creatures gets into the body of a supermarket cashier Jeong Soo-yeon, but he fails to capture her brain, as a result of which the two, who have formed a kind of symbiosis, are forced to coexist with each other. Soon, the fate of the main character is intertwined with the fate of two more people: a small-time gangster Sol Kang-woo, who is looking for his missing sister, and Choi Joon—kyung, the leader of a secret task force called the "Greys", who is looking for a way to defeat the parasites.',
        aboutRu: 'Существа-паразиты, прибывшие на Землю из глубин космоса, начинают постепенно проникать в тела людей, беря их под контроль, чтобы в перспективе подчинить себе все человечество. Одно из существ попадает в тело кассирши из супермаркета Чон Су-ин, однако ему не удаётся захватить её мозг, в результате чего двое, образовавшие своеобразный симбиоз, вынуждены сосуществовать друг с другом. Вскоре судьба главной героини переплетается с судьбами еще двух человек: мелкого гангстера Соль Кан-у, разыскивающего свою исчезнувшую сестру, и Чхве Джун-ген — лидера секретной оперативной группы под названием «Серые», которая ищет способ победить паразитов.',
        rating: 4.2
    },
    {
        id: 5,
        nameEn: 'Sugar',
        nameRu: 'Шугар',
        imgSm: 'sugar-min.jpg',
        imgLg: 'sugar-md.jpg',
        video: 'Sugar — Official Trailer _ Apple TV .mp4',
        duration: 50,
        year: 2024,
        type: 'series',
        director: 'Mark Protosevich',
        actors: ['Colin Farrell','Kirby','Amy Ryan','Dennis Boutsikaris'],
        category: ['criminal','drama'],
        aboutEn: 'A mysterious private detective investigates the disappearance of the granddaughter of a Hollywood producer and simultaneously fights his own demons.',
        aboutRu: 'Загадочный частный детектив расследует исчезновение внучки голливудского продюсера и одновременно сражается с собственными демонами.',
        rating: 4.3
    },
    {
        id: 6,
        nameEn: 'Ripley',
        nameRu: 'Рипли',
        imgSm: 'ripley-min.jpg',
        imgLg: 'ripley-md.jpg',
        video: 'Ripley _ Official Teaser _ Netflix.mp4',
        duration: 56,
        year: 2024,
        type: 'series',
        director: 'Andrew Scott',
        actors: ['Dakota Fanning','Andrew Scott','Johnny Flynn','Margherita Buy','Vittorio Viviani'],
        category: ['criminal','drama','thriller'],
        aboutEn: 'The 1960s. A rich man hires a small-time crook, Tom Ripley, to go to Italy and bring his stupid son back to the States.',
        aboutRu: '1960-е. Богач нанимает мелкого мошенника Тома Рипли, чтобы тот отправился в Италию и вернул в Штаты его бестолкового сына.',
        rating: 4.6
    },
    {
        id: 7,
        nameEn: 'Parish / The Driver',
        nameRu: 'Пэриш',
        imgSm: 'parish-the-driver-min.jpg',
        imgLg: 'parish-the-driver-md.jpg',
        video: 'Parish Official Trailer feat. Giancarlo Esposito _ Premieres March 31 _ AMC .mp4',
        duration: 45,
        year: 2024,
        type: 'series',
        director: 'Giancarlo Esposito',
        actors: ['Giancarlo Esposito','Zackary Momoh','Paula Malcomson','Skeet Ulrich'],
        category: ['criminal','drama','thriller'],
        aboutEn: 'The action develops around Gracian Parish, a man with a dark past who left his former life. Struggling with financial problems and personal difficulties, compounded by the tragic death of his son, he struggles to start life from scratch. When his old friend Colin turns to him for help, seeking to repay a debt to a Zimbabwean crime boss, Parish reluctantly agrees to return to the underworld as a professional driver for bandits. As soon as the carefully planned robbery gets out of control, Gracian finds himself involved in the criminal activities of gangsters from Zimbabwe.',
        aboutRu: 'Действие развивается вокруг Грасиана Пэриша — человека с темным прошлым, который оставил былую жизнь. Ведя борьбу с финансовыми проблемами и личными трудностями, усугубляемыми трагической смертью сына, он изо всех сил пытается начать жизнь с нуля. Когда к нему за помощью обращается его старый друг Колин, стремящийся погасить долг перед зимбабвийским криминальным авторитетом, Пэриш неохотно соглашается вернуться в преступный мир в качестве профессионального водителя для бандитов. Как только тщательно спланированное ограбление выходит из-под контроля, Грасиан оказывается вовлеченным в криминальную деятельность гангстеров из Зимбабве.',
        rating: 4.8
    },
    {
        id: 8,
        nameEn: 'A Gentleman in Moscow',
        nameRu: 'Джентльмен в Москве',
        imgSm: 'a-gentleman-in-moscow-min.jpg',
        imgLg: 'a-gentleman-in-moscow-md.jpg',
        video: 'A Gentleman in Moscow _ Official Trailer _ SHOWTIME.mp4',
        duration: 50,
        year: 2024,
        type: 'series',
        director: 'Ewan McGregor',
        actors: ['Ewan McGregor','Daniel Cerqueira','Johnny Harris','Leah Harvey'],
        category: ['drama','thriller'],
        aboutEn: 'In 1922, the Bolsheviks sentenced the eccentric Count Alexander Rostov to house arrest in the luxurious Metropol Hotel, located next to the Kremlin. Being a literate, erudite and witty man, Rostov is forced to be locked up and under constant supervision, which contradicts his usual lifestyle. While Alexander is trying to adapt to new circumstances, extremely turbulent events are taking place outside the hotel, which are destined to become an integral part of Russian history. Everything changes when the count\'s limited circumstances open the way for him into the wonderful world of emotional discoveries.',
        aboutRu: 'В 1922 году большевики приговаривают эксцентричного графа Александра Ростова к домашнему аресту в роскошном отеле «Метрополь», расположенном рядом с Кремлем. Будучи грамотным, эрудированным и остроумным мужчиной, Ростов вынужден находиться взаперти и под постоянным присмотром, что противоречит его привычному образу жизни. Пока Александр пытается приспособиться к новым обстоятельствам, за дверями гостиницы происходят чрезвычайно бурные события, которым суждено стать неотъемлемой частью российской истории. Все меняется, когда ограниченные обстоятельства графа открывают ему путь в удивительный мир эмоциональных открытий.',
        rating: 4.8
    },
    {
        id: 9,
        nameEn: 'Manhunt',
        nameRu: 'Охота за убийцей',
        imgSm: 'manhunt-min.jpg',
        imgLg: 'manhunt-md.jpg',
        video: 'Manhunt — Official Trailer _ Apple TV .mp4',
        duration: 55,
        year: 2024,
        type: 'series',
        director: 'Monica Beletsky',
        actors: ['Tobias Menzies','Anthony Boyle','Lovie Simone','Will Harrison'],
        category: ['drama','thriller'],
        aboutEn: 'Based on the novel by James Swanson, The Manhunt: 12 Days of the Chase for the Lincoln Killer. About the most notorious crime of the 19th century — the assassination of US President Abraham Lincoln. He was shot dead at Ford\'s Theater during a performance. Secretary of War Edwin Stanton is searching for actor John Wilkes Booth, who shot at the president in the theater box. Smart and meticulous, Stanton is determined to find the killer and take revenge at all costs.',
        aboutRu: 'По роману Джеймса Суонсона «Охота на человека: 12 дней погони за убийцей Линкольна». О самом громком преступлении 19 века — убийстве президента США Авраама Линкольна. Его застрелили в театре Форда во время представления. Военный министр Эдвин Стэнтон занимается поисками стрелявшего в президента в театральной ложе актера Джона Уилкса Бута. Умный и педантичный Стэнтон полон решимости во что бы то ни стало отыскать убийцу и отомстить.',
        rating: 4.9
    },
    {
        id: 10,
        nameEn: 'The Gentlemen',
        nameRu: 'Джентльмены',
        imgSm: 'the-gentlemen-min.jpg',
        imgLg: 'the-gentlemen-md.jpg',
        video: 'Джентльмены (1 сезон) — Русский трейлер (4К, Субтитры, 2024).mp4',
        duration: 50,
        year: 2024,
        type: 'series',
        director: 'Guy Ritchie',
        actors: ['Theo James','Kaya Scodelario','Daniel Ings','Joely Richardson','Vinnie Jones'],
        category: ['comedy','criminal','action'],
        aboutEn: 'A young captain of the British army, Eddie, returns to the luxurious family estate to say goodbye to his dying aristocrat father. Upon reading the will, he is surprised to learn that he has bypassed his wayward older brother Freddie in the right to inherit all the property. Even more surprising is the fact that shortly before his death, his father made a deal with criminal entrepreneur Susie Glass, who uses his estate as a cover for a cannabis farm. To make matters worse, several local powerful gangsters are claiming a share of the profits. To keep the family out of trouble, Eddie begins to take drastic measures and gradually gets a taste of illegal business.',
        aboutRu: 'Молодой капитан британской армии Эдди возвращается в роскошное родовое поместье, чтобы проститься с умирающим отцом-аристократом. На прочтении завещания он с удивлением узнает, что обошел своего непутевого старшего брата Фредди в праве на наследство всего имущества. Еще большей неожиданностью становится тот факт, что незадолго до смерти отец заключил сделку с криминальной предпринимательницей Сьюзи Гласс, которая использует его поместье как прикрытие для фермы по выращиванию каннабиса. Что еще хуже, несколько местных влиятельных гангстеров претендуют на долю от прибыли. Чтобы уберечь семью от неприятностей, Эдди начинает принимать решительные меры и постепенно входит во вкус нелегального бизнеса.',
        rating: 4.9
    },
    {
        id: 11,
        nameEn: 'Game of Thrones',
        nameRu: 'Игра престолов',
        imgSm: 'game-of-thrones-min.jpg',
        imgLg: 'game-of-thrones-md.jpg',
        video: 'Game of Thrones _ Season 8 _ Official Trailer (HBO).mp4',
        duration: 55,
        year: 2011,
        type: 'series',
        director: 'David Bennioff',
        actors: ['Emilia Clarke','Peter Dinklage','Kit Harington','Lena Headey','Sophie Turner'],
        category: ['fantasy','drama','adventure'],
        aboutEn: 'After an uprising provoked by the actions of the insane ruler of Westeros, Robert of the House of Baratheon sits on the Iron Throne, becoming the new ruler of the Seven Kingdoms. Years later, John Arryn, the hand of the king, dies, and Robert goes on a campaign to enlist the support of his childhood friend Eddard Stark, the Guardian of the North. The ambitious and noble head of the House of Stark has been instructed to leave his native monastery and become the new hand of the king. Secretly warned that Arryn was actually killed and Robert could be the next victim, Eddard tries to fix the situation, but political intrigues, conspiracies, murders and the escalated struggle for the Iron Throne lead to large-scale upheavals in Westeros...',
        aboutRu: 'После восстания, спровоцированного действиями безумного правителя Вестероса, Роберт из дома Баратеонов восседает на Железный трон, став новым правителем Семи королевств. Годы спустя Джон Аррен, десница короля, умирает, а Роберт отправляется в поход, чтобы заручиться поддержкой друга детства — Эддарда Старка, Хранителя Севера. Честолюбивому и благородному главе дома Старков поручено покинуть родную обитель и стать новым десницей короля. Тайно предупрежденный о том, что Аррен на самом деле был убит, а Роберт может стать следующей жертвой, Эддард пытается исправить ситуацию, но политические интриги, заговоры, убийства и обострившаяся борьба за Железный трон приводят к масштабным потрясениям в Вестеросе...',
        rating: 4.9
    },
    {
        id: 12,
        nameEn: 'Sherlock',
        nameRu: 'Шерлок',
        imgSm: 'sherlock-min.jpeg',
        imgLg: 'sherlock-md.jpeg',
        video: 'Сериал _Шерлок_. Русский трейлер..mp4',
        duration: 90,
        year: 2010,
        type: 'series',
        director: 'Mark Gatiss',
        actors: ['Benedict Cumberbatch','Martin Freeman','Una Stubbs','Rupert Graves'],
        category: ['thriller','drama','criminal'],
        aboutEn: 'A free interpretation of the cycle of cult stories about the brilliant British detective, where this time the events are transferred to the XXI century. In the story, military doctor John Watson, who suffers from leg pain after serving in Afghanistan, returns to London, where he is looking for a suitable apartment. He stops at Baker Street with the good-natured Mrs. Hudson, along with an astute detective named Sherlock Holmes. Using methods of observation, analysis, deduction and applying modern technologies, they help the metropolitan police solve the most difficult cases.',
        aboutRu: 'Вольная интерпретация цикла культовых рассказов о гениальном британском сыщике, где на этот раз события переносятся в XXI век. По сюжету военный врач Джон Ватсон, после службы в Афганистане страдающий от боли в ноге, возвращается в Лондон, где подыскивает себе подходящую квартиру. Он останавливается на Бейкер-стрит у добродушной миссис Хадсон вместе с проницательным детективом по имени Шерлок Холмс. Используя методы наблюдения, анализа, дедукции и применяя современные технологии, они помогают столичной полиции раскрывать наиболее сложные дела.',
        rating: 4.8,
    },
    {
        id: 13,
        nameEn: 'The Grand Tour',
        nameRu: 'Гранд тур',
        imgSm: 'the-grand-tour-min.jpg',
        imgLg: 'the-grand-tour-md.jpg',
        video: 'The Grand Tour _ Season 1 _ Official Trailer.mp4',
        duration: 60,
        year: 2016,
        type: 'series',
        director: 'Jeremy Clarkson',
        actors: ['Jeremy Clarkson','James May','Richard Hammond','Abbie Eaton'],
        category: ['comedy'],
        aboutEn: 'An American automotive television show hosted by former participants of the world-famous Top Gear project Jeremy Clarkson, Richard Hammond and James May with financial support from Amazon Prime. Rumors about the possible creation of another TV show featuring the famous trio began to appear immediately after Clarkson\'s scandalous dismissal from the popular BBC program and the subsequent departure of his fellow presenters and executive producer Andy Wilman. For a long time, fans have been collecting information bit by bit, first learning about some details of the contract, and then about the planned name of the new TV project and the expected release date. As it turned out, the creators plan to release three seasons of twelve episodes each, while using the format of separate TV movies combining on-site and studio filming. The triumphant return of the beloved presenters turned out to be more than grandiose, because already in the pilot release of the long-awaited auto show called The Grand Tour, you can easily appreciate its scale, as well as the inexhaustible optimism of its main inspirers, who remain devoted to their favorite business even despite various difficult life circumstances. Now they travel all over the world again and willingly share with millions of TV viewers their extensive knowledge in the field of auto journalism, demonstrating equally well both their knowledge of theory and practical driving skills of the best representatives of the modern automotive industry.',
        aboutRu: 'Американское автомобильное телевизионное шоу, организованное бывшими участниками всемирно известного проекта Top Gear Джереми Кларксоном, Ричардом Хаммондом и Джеймсом Мэйем при финансовой поддержке сервиса Amazon Prime. Слухи о возможном создании другого телешоу с участием знаменитой троицы начали появляться сразу же после скандального увольнения Кларксона из популярной передачи канала BBC и последовавшего за этим ухода его коллег-ведущих и исполнительного продюсера Энди Уилмана. Долгое время фанаты по крупицам собирали информацию, вначале узнав о некоторых деталях контракта, а затем о планируемом наименовании нового телепроекта и ожидаемой дате его выхода. Как оказалось, создатели планируют выпустить три сезона по двенадцать эпизодов в каждом, при этом будет использоваться формат отдельных телефильмов, сочетающих выездные и студийные съемки. Триумфальное возвращение полюбившихся ведущих выдалось более чем грандиозным, ведь уже в пилотном выпуске долгожданного автошоу под названием The Grand Tour можно легко ценить его масштабность, так же как и неиссякаемый оптимизм его основных вдохновителей, остающихся преданными своему любимому делу даже несмотря на различные сложные жизненные обстоятельства. Теперь они вновь путешествуют по всему миру и охотно делятся с миллионами телезрителей своими обширными знаниями в сфере автожурналистики, одинаково хорошо демонстрируя как владение теорией, так и практические навыки вождения лучших представителей современного автопрома.',
        rating: 4.8,
    },
    {
        id: 14,
        nameEn: 'The Sopranos',
        nameRu: 'Клан Сопрано',
        imgSm: 'the-sopranos-min.jpeg',
        imgLg: 'the-sopranos-md.jpeg',
        video: 'The Sopranos _Family. Redefined_ Trailer.mp4',
        duration: 55,
        year: 1999,
        type: 'series',
        director: 'David Chase',
        actors: ['James Gandolfini','Lorraine Bracco','Edie Falco','Michael Imperioli','Steven Van Zandt'],
        category: ['criminal','drama'],
        aboutEn: 'After the sudden death of northern New Jersey mafia boss Jackie Aprile, his right-hand man Tony Soprano becomes the new leader of an influential criminal family, but not all of its members agree with his appointment. Anthony suffers a nervous breakdown from fallen responsibilities and increased responsibility and makes an appointment with a psychotherapist Jennifer Melfi, who is primarily interested in the details of his life and work. Constrained by the obligation to remain silent, the main character tries to combine visiting a doctor and the active life of a mafia boss.',
        aboutRu: 'После скоропостижной смерти босса мафии северного Нью-Джерси Джеки Априла, его правая рука Тони Сопрано становится новым лидером влиятельной криминальной семьи, однако далеко не все её члены согласны с его назначением. От свалившихся обязанностей и возросшей ответственности Энтони переживает нервный срыв и записывается на прием к психотерапевту Дженнифер Мелфи, которая в первую очередь интересуется подробностями его жизни и работы. Скованный обязательством хранить молчание, главный герой пытается совмещать посещение доктора и активную жизнь босса мафии.',
        rating: 4.9,
    },
    {
        id: 15,
        nameEn: 'House M.D.',
        nameRu: 'Доктор Хаус',
        imgSm: 'house-m-d-min.jpeg',
        imgLg: 'house-m-d-md.jpeg',
        video: 'House M.D. Season 8 - Official Trailer for the New Season.mp4',
        duration: 43,
        year: 2004,
        type: 'series',
        director: 'David Shore',
        actors: ['Hugh Laurie','Omar Epps','Robert Sean Leonard','Jesse Spencer','Lisa Edelstein'],
        category: ['drama'],
        aboutEn: 'The action revolves around Dr. Gregory House, a charismatic and incredibly talented doctor with sociopathic tendencies, who became addicted to painkillers because of the pain that haunts him. As the head of a team of doctors, including Robert Chase, Allison Cameron and Eric Foreman, specializing in the diagnosis of diseases, Dr. House undertakes the treatment of atypical and rare cases. However, the difficult nature, the desire to violate generally accepted rules and dependence on Vicodin lead to constant conflicts between House and the chief physician of the clinic, Lisa Cuddy, and James Wilson, the head of the oncology department and his best friend, helps the hero solve numerous ethical dilemmas.',
        aboutRu: 'Действие разворачивается вокруг доктора Грегори Хауса — харизматичного и невероятно талантливого врача с наклонностями социопата, который из-за преследующих его болей пристрастился к болеутоляющим средствам. Будучи начальником команды врачей, включающей Роберта Чейза, Эллисон Кэмерон и Эрика Формана, специализирующихся на диагностике заболеваний, доктор Хаус берется за лечение нетипичных и редких случаев. Однако непростой характер, стремление нарушать общепринятые правила и зависимость от «Викодина» приводят к постоянным конфликтам между Хаусом и главным врачом клиники Лизой Кадди, а решать многочисленные этические дилеммы герою помогает Джеймс Уилсон — глава онкологического отделения и его лучший друг.',
        rating: 4.4,
    },
    {
        id: 16,
        nameEn: 'Chernobyl',
        nameRu: 'Чернобыль',
        imgSm: 'chernobyl-min.jpg',
        imgLg: 'chernobyl-md.jpg',
        video: 'Чернобыль _ Трейлер.mp4',
        duration: 56,
        year: 2019,
        type: 'series',
        director: 'Craig Mazin',
        actors: ['Jessie Buckley','Jared Harris','Stellan Skarsgård','Adam Nagaitis','Emily Watson'],
        category: ['drama'],
        aboutEn: 'The plot of the mini-series is centered on one of the largest man-made disasters of our time - the accident at the Chernobyl nuclear power plant in 1986. This is a story about the incredible courage and self-sacrifice of ordinary people who were engaged in eliminating the horrific consequences of the destruction of a nuclear reactor, as well as helping to evacuate the local population living in a 30-kilometer zone around the accident site.',
        aboutRu: 'В центре сюжета мини-сериала находится одна из крупнейших техногенных катастроф современности - авария на Чернобыльской АЭС в 1986 году. Это история о невероятном мужестве и самопожертвовании простых людей, которые занимались ликвидацией ужасающих последствий разрушения ядерного реактора, а также помогали эвакуировать местное население, проживающее в 30-километровой зоне вокруг места аварии.',
        rating: 5,
    },
    {
        id: 17,
        nameEn: 'Yellowstone',
        nameRu: 'Йеллоустоун',
        imgSm: 'yellowstone-min.jpg',
        imgLg: 'yellowstone-md.jpg',
        video: 'YELLOWSTONE Official Trailer (2018) Kevin Costner, TV Series HD.mp4',
        duration:  50,
        year: 2018,
        type: 'series',
        director: 'John Linson',
        actors: ['Kevin Costner','Luke Grimes','Kelly Reilly','Wes Bentley'],
        category: ['drama','criminal'],
        aboutEn: 'The plot of the series is centered on members of the Dutton family, who own a large ranch on the border with a national park and an Indian reservation. The heroes are constantly under pressure, as everyone wants to get their land: the state, Indians and greedy developers. This place is both the most beautiful and the scariest corner of America, for which unsolved murders and poisoned water in wells are commonplace. John Dutton is trying to do everything possible to protect his family and the family legacy that they want to take away from them at any cost.',
        aboutRu: 'В центре сюжета сериала оказывают члены семьи Даттон, владеющие большим ранчо на границе с национальным парком и индейской резервацией. Герои постоянно находятся под давлением, так как все хотят заполучить их землю: государство, индейцы и жадные застройщики. Это место является одновременно самым прекрасным и самым страшным уголком Америки, для которого нераскрытые убийства и отравленная вода в колодцах являются обыденностью. Джон Даттон старается сделать все возможное для защиты своей семьи и семейного наследия, которое у них хотят отобрать любой ценой.',
        rating: 4.7,
    },
    {
        id: 18,
        nameEn: 'The Chosen',
        nameRu: 'Избранные',
        imgSm: 'the-chosen-min.jpg',
        imgLg: 'the-chosen-md.jpg',
        video: 'The Chosen _ Official Trailer HD.mp4',
        duration: 50,
        year: 2017,
        type: 'series',
        director: 'Dallas Jenkis',
        actors: ['Elizabeth Tabish','Jonathan Roumie','Shahar Isaac','Nick Shakoour','Jordan Walker Ross'],
        category: ['drama'],
        aboutEn: 'Events begin to develop in 26 AD in Capernaum, under the control of the Roman Empire, around several biblical characters at once, whose future destinies will be closely intertwined with the wandering preacher Jesus Christ. The key role in the plot is played by the penitent harlot Mary Magdalene, tormented by internal demons; a member of the Sanhedrin Nicodemus, persecuted by the local authorities; the fishermen brothers and future apostles Simon and Andrew; as well as Levi Matthew, a tax collector who will become the author of the first canonical Gospel.',
        aboutRu: 'События начинают развиваться в 26 году н.э. в Капернауме, находящемся под контролем Римской империи, вокруг сразу нескольких библейских персонажей, чьи дальнейшие судьбы будут тесно переплетены со странствующим проповедником Иисусом Христом. Ключевую роль в сюжете играют кающаяся блудница Мария Магдалина, терзаемая внутренними демонами; член синедриона Никодим, преследуемый местной властью; братья-рыбаки и будущие апостолы Симон и Андрей; а также сборщик налогов Левий Матфей, который станет автором первого канонического Евангелия.',
        rating: 5,
    },
    {
        id: 19,
        nameEn: 'Aile',
        nameRu: 'Семья',
        imgSm: 'aile-min.jpg',
        imgLg: 'aile-md.jpg',
        video: 'Aile ❖ Ep 1 Trailer .mp4',
        duration: 120,
        year: 2023,
        type: 'series',
        director: 'Kivanç Tatlitug',
        actors: ['Kivanç Tatlitug','Serenay Sarikaya','Nur Sürer','Nejat Isler'],
        category: ['drama','action','criminal'],
        aboutEn: 'Aslan Soikan is a young heir to the influential Izmir mafia, combining gloom, mystery and insight. One day, he boards a plane to Izmir to solve one of his "dark cases" concerning his family. On board, a man makes acquaintance with a charming woman psychologist Devin Akin, who in turn flies to the city to deal with her sister\'s new trouble. Aslan and Devin, existing in completely different worlds, suddenly find each other a lot in common and find mutual love full of unpredictable twists of fate.',
        aboutRu: 'Аслан Сойкан — молодой наследник влиятельный измирской мафии, сочетающий в себе мрачность, загадочность и проницательность. Однажды он садится на самолет в Измир, чтобы решить одно из своих «темных дел», касающихся семьи. На борту мужчина заводит знакомство с очаровательной женщиной-психологом Девин Акин, которая в свою очередь летит в город, чтобы разобраться с новой бедой своей сестры. Аслан и Девин, существующие в абсолютно разных мирах, неожиданно находят друг у друга много общего и обретают взаимную любовь, полную непредсказуемых поворотов судьбы.',
        rating: 5,
    },
    {
        id: 20,
        nameEn: 'Shameless',
        nameRu: 'Бесстыжие / Бесстыдники',
        imgSm: 'shameless-min.jpg',
        imgLg: 'shameless-md.jpg',
        video: 'Shameless Season 11 (2020) Official Trailer _ William H. Macy SHOWTIME Series.mp4',
        duration: 55,
        year: 2011,
        type: 'series',
        director: 'Paul Abbott',
        actors: ['Emmy Rossum','William H. Macy','Ethan Cutkosky','Jeremy Allen White','Shanola Hampton'],
        category: ['drama','comedy'],
        aboutEn: 'The action takes place in one of the poorest neighborhoods of Chicago around the dysfunctional Gallagher family. The head of the family, Frank Gallagher, is a chronic alcoholic and a small—time fraudster who spends his days trying to get easy money for drinks. While he gets into various troubles, completely ignoring his children, his eldest daughter Fiona is forced to take on the role of guardian for younger siblings — Lip, Ian, Debbie, Carl and Liam. Relying solely on each other\'s help, the Gallaghers learn to live independently, grow up, enter into romantic relationships and try to achieve their goals at all costs.',
        aboutRu: 'Действие развивается в одном из беднейших районов Чикаго вокруг неблагополучной семьи Галлагеров. Глава семейства Фрэнк Галлагер — хронический алкоголик и мелкий мошенник, проводящий дни напролет в попытках раздобыть легкие деньги на выпивку. Пока он попадает в различные неприятности, совершенно не уделяя внимания своим детям, его старшая дочь Фиона вынуждена взять на себя роль опекуна для младших братьев и сестры — Липа, Йена, Дебби, Карла и Лиама. Рассчитывая исключительно на помощь друг друга, Галлагеры учатся самостоятельной жизни, взрослеют, вступают в романтические отношения и пытаются во что бы то ни стало добиться поставленных целей.',
        rating: 4.5,
    },
    {
        id: 21,
        nameEn: 'The office',
        nameRu: 'Офис',
        imgSm: 'the-office-min.jpg',
        imgLg: 'the-office-md.jpg',
        video: 'The Office US Season 1 Trailer (2005).mp4',
        duration: 22,
        year: 2005,
        type: 'series',
        director: 'Greg Daniels',
        actors: ['Steve Carell','Jenna Fischer','John Krasinski','Rainn Wilson','Brian Baumgartner'],
        category: ['comedy'],
        aboutEn: 'The plot centers on employees of the regional office of the Dunder Mifflin company, whose duties include finding customers to sell paper products. The department is headed by the eccentric and never-losing sense of humor Michael Scott, who unashamedly considers himself the best boss, while his subordinates do anything but work during their working days. Against the background of the irresponsible team, Dwight Schrute, a stern patriot of his cause, deliberately stands out, who acts as the source of most of the comical moments in the series, opposing a young and frivolous colleague Jim Halpert.',
        aboutRu: 'В центре сюжета сотрудники регионального офиса компании «Dunder Mifflin», в чьи обязанности входит нахождение клиентов для продажи бумажной продукции. Руководит отделом эксцентричный и никогда не теряющий чувства юмора Майкл Скотт, который без стеснения считает себя самым лучшим боссом, в то время как его подчиненные в трудовые будни занимаются чем угодно кроме работы. На фоне безответственно коллектива нарочито выделяется суровый патриот своего дела Дуайт Шрут, который выступает источником большинства комичных моментов в сериале, противостоя молодому и легкомысленному коллеге Джиму Халперту.',
        rating: 4.8,
    },
    {
        id: 22,
        nameEn: 'The Big Bang Theory',
        nameRu: 'Теория большого взрыва',
        imgSm: 'the-big-bang-theory-min.jpg',
        imgLg: 'the-big-bang-theory-md.jpg',
        video: 'The Big Bang Theory Trailer.mp4',
        duration: 22,
        year: 2007,
        type: 'series',
        director: 'Chuck Lorre',
        actors: ['Johnny Galecki','Jim Parsons','Kaley Cuoco','Simon Helberg','Kunal Nayyar'],
        category: ['comedy'],
        aboutEn: 'The Big Bang Theory is perhaps one of the best comedy series, the so-called sitcoms, of the last decade, which symbolizes a new era, like the TV series "Friends" at the time. Bright and atypical characters, wonderful acting, great humor – these are just a few of the advantages of the series, because of which you just need to get into the screen and watch it. This is one of those series that you must definitely watch, and which does not bother you at all.\n' +
            'The plot centers on two young and talented physicists – Leonard and Sheldon. They are very smart, and frankly, consider themselves "great minds." But, despite the fact that their IQ is off the scale, guys absolutely cannot communicate with people, especially if it concerns an attractive girl. However, with the advent of a new neighbor, the stunning beauty Penny, everything begins to change dramatically.\n' +
            'Leonard and Sheldon\'s company is complemented by two of their slightly unusual friends, one of whom is a lustful engineer Howard Wolowitz, and the second is an unrealistically shy astrophysicist Rajesh Koothrappali, who needs a good drink before talking to a girl, not to mention something more.',
        aboutRu: 'Теория большого взрыва, пожалуй, один из самых лучших комедийных сериалов, так называемых ситкомов, последнего десятилетия, который символизирует собой новую эпоху, как в свое время сериал «Друзья». Яркие и нетипичные персонажи, замечательная игра актеров, отличный юмор – это всего лишь несколько достоинств сериала, из-за которых просто нужно влипнуть в экран и посмотреть его. Это один из тех сериалов, который нужно обязательно смотреть, и который совсем не надоедает.\n' +
            'В центре сюжета двое молодых и талантливых физиков – Леонард и Шелдон. Они очень умны, и откровенно говоря, считают себя «великими умами». Но, несмотря на то, что их IQ зашкаливает, парни совершенно не могут общаться с людьми, тем более, если это касается привлекательной девушки. Однако с появлением новой соседки, сногсшибательной красотки Пенни, все начинает меняться кардинальным образом.\n' +
            'Компанию Леонарда и Шелдона дополняют двое их немного необычных друзей, один из которых - похотливый инженер Говард Воловиц, а второй - нереально застенчивый астрофизик Раджеш Кутраппали, которому нужно хорошенько выпить перед тем, как заговорить с девушкой, не говоря уже о чем-то большем.',
        rating: 4.5,
    },
    {
        id: 23,
        nameEn: 'Taskmaster',
        nameRu: 'Таскмастер',
        imgSm: 'taskmaster-min.jpg',
        imgLg: 'taskmaster-md.jpg',
        video: 'Brand New Taskmaster Coming Soon..mp4',
        duration: 45,
        year: 2015,
        type: 'series',
        director: 'Greg Davies',
        actors: ['Greg Davies','Alex Horne','Kerry Godliman','Ed Gamble','Sarah Kendall','Sophie Duker'],
        category: ['comedy'],
        aboutEn: 'British comedian and actor Greg Davis and his constant assistant Alex Horn challenge a group of five participants, who are comedians and famous TV presenters, who will compete with each other in performing wacky and funny tasks prepared by the entertainment show team. By completing fun tasks, the participants of the show receive points for passing the tests, and eventually the player with the highest score wins a set of various prizes that were provided by the participants themselves…',
        aboutRu: 'Британский комик и актер Грег Дэвис и его неизменный помощник Алекс Хорн бросают вызов группе из пяти участников, являющихся комиками и известными телеведущими, которым предстоит соревноваться друг с другом в выполнении дурацких и смешных заданий, подготовленных командой развлекательного шоу. Выполняя забавные задачи, участники шоу получают очки за прохождение испытаний, а в конечном итоге игрок, набравший наибольшее количество баллов, выигрывает набор различных призов, которые были предоставлены самими участниками…',
        rating: 4.8,
    },
    {
        id: 24,
        nameEn: 'Anne',
        nameRu: 'Энн',
        imgSm: 'anne-min.jpg',
        imgLg: 'anne-md.jpg',
        video: 'Anne _ Official Trailer [HD] _ Netflix.mp4',
        duration: 45,
        year: 2017,
        type: 'series',
        director: 'Moira Walley-Beckett',
        actors: ['Amybeth McNulty','Geraldine James','R.H. Thomson','Andrea Arruti','Dalila Bela'],
        category: ['drama'],
        aboutEn: 'The series is set in the late 19th century on Prince Edward Island. The elderly brother and sister Matthew and Marilla Cuthbert decide to adopt a boy to help on their family farm. When Matthew goes to the railway station to pick up the child, he is surprised to find only red–haired Ann there - an energetic and talkative thirteen-year-old orphan with a difficult fate, who was sent as a result of a mix-up. At first, Cuthbert intends to return Ann to the orphanage, but over time, the girl manages to melt their hearts and become an integral part of the small town that helped her find a real home. …',
        aboutRu: 'Действие сериала разворачивается в конце 19-го века на острове Принца Эдуарда. Пожилые брат и сестра Мэтью и Марилла Катберты решают усыновить мальчика для помощи на их семейной ферме. Когда Мэтью отправляется на железнодорожную станцию, чтобы забрать ребенка, он с удивлением обнаруживает там лишь рыжеволосую Энн – энергичную и разговорчивую тринадцатилетнюю сироту с непростой судьбой, которую прислали в результате путаницы. Поначалу Катберты намереваются вернуть Энн в приют, однако со временем девочке удается растопить их сердца и стать неотъемлемой частью маленького городка, который помог ей обрести настоящий дом …',
        rating: 4.8,
    },
    {
        id: 25,
        nameEn: 'The Offer',
        nameRu: 'Предложение',
        imgSm: 'the-offer-min.jpg',
        imgLg: 'the-offer-md.jpg',
        video: 'The Offer _ Official Trailer _ Paramount .mp4',
        duration: 50,
        year: 2022,
        type: 'series',
        director: 'Leslie Greif',
        actors: ['Miles Teller','Matthew Goode','Dan Fogler','Burn Gorman','Colin Hanks'],
        category: ['drama'],
        aboutEn: 'In the late 1960s, the unsuccessful writer Mario Puzo, mired in debt, writes The Godfather, his best novel, which tells about the Corleone gangster family. The book quickly becomes a bestseller, and several Hollywood studios, including Paramount Pictures, begin to fight for its adaptation. Aspiring producer Albert Ruddy, who received the right to create the film, attracts promising director Francis Ford Coppola to the shooting. At the same time, Italian mobster Joseph Colombo and singer Frank Sinatra, offended by the plot of the novel, take drastic measures to prevent the filming from taking place.',
        aboutRu: 'В конце 1960-х годов неудачливый писатель Марио Пьюзо, погрязший в долгах, пишет «Крестный отец», свой лучший роман, в котором рассказывается о гангстерской семье Корлеоне. Книга быстро становится бестселлером, а за ее экранизацию начинают бороться сразу несколько голливудских студий, в том числе Paramount Pictures. Начинающий продюсер Альберт Радди, получивший право на создание фильма, привлекает к съемкам перспективного режиссера Фрэнсиса Форда Копполу. В то же время итальянский мафиози Джозеф Коломбо и певец Фрэнк Синатра, оскорбленные сюжетом романа, идут на решительные меры, чтобы не дать съемкам состояться.',
        rating: 4.6,
    },
    {
        id: 26,
        nameEn: 'Superninja',
        nameRu: 'Суперниндзя',
        imgSm: 'superninja-min.jpg',
        imgLg: 'superninja-md.jpg',
        video: 'Суперниндзя _ СТС Премьера _ Анонс.mp4',
        duration: 120,
        year: 2023,
        type: 'series',
        director: 'Юрий Кондратюк',
        actors: ['Valeriya Astapova','Vasiliy Artemiev','Dmitriy Maslennikov','Roman Postovalov'],
        category: ['comedy'],
        aboutEn: 'The television project of the CTC channel, which is an extreme competition of athletes from all over our country. Demonstrating the wonders of strength, endurance and high speed, athletes overcome a track specially designed for the show with various types of obstacles and collect rings. The more incendiary rings a participant collects while fighting against obstacles, the higher his chances of becoming one of the thirty-five finalists, the end point of which will be the last artifact located at a height of twenty-six meters.',
        aboutRu: 'Телевизионный проект канала СТС, представляющий собой экстремальное соревнование атлетов со всех уголков нашей страны. Демонстрируя чудеса силы, выносливости и высокой скорости спортсмены преодолевают специально разработанную для шоу трассу с разного вида препятствиями и собирают кольца. Чем больше зажигающихся колец наберет участник, сражаясь с преградами, тем выше его шансы стать одним из тридцати пяти финалистов, конечной точкой которых будет последний артефакт, расположенный на высоте двадцати шести метров.',
        rating: 4.6,
    },
    {
        id: 27,
        nameEn: 'Young Sheldon',
        nameRu: 'Детство Шелдона / Юный Шелдон',
        imgSm: 'yound-sheldon-min.jpg',
        imgLg: 'yound-sheldon-md.jpg',
        video: 'YOUNG SHELDON Trailer Promos Season 1 (2017) Big Bang Theory Spinoff Series.mp4',
        duration: 30,
        year: 2017,
        type: 'series',
        director: 'Chuck Lorre',
        actors: ['Iain Armitage','Zoe Perry','Montana Jordan','Raegan Revord','Jim Parsons'],
        category: ['comedy'],
        aboutEn: 'The series tells about the difficult but extremely fun life of nine–year-old Sheldon Cooper, a gifted boy who considers himself the only mind in his generation capable of mathematics and exact sciences. But all his abilities are not very useful in East Texas, where religious education and sports are much more important than complex mathematical formulas and incredible conclusions. In addition, while a gifted, slightly naive kid, focused on studying exact sciences instead of developing social skills, is trying to interact with the outside world, the Cooper family, which is the most ordinary American family, is constantly, but not always successfully, trying to find a common language with its overly intelligent talent. This creates a lot of comical situations in which not only our hero gets into, but also his entire environment.',
        aboutRu: 'Сериал расскажет о непростой, но чрезвычайно веселой жизни девятилетнего Шелдона Купера – одарённого паренька, считающего себя единственным в своём поколении умом, способным к математике и точным наукам. Вот только все его способности оказываются не очень полезными в Восточном Техасе, где религиозное воспитание и занятие спортом намного важнее сложных математических формул и невероятных умозаключений. К тому же, пока одарённый, слегка наивный малыш, сконцентрированный на изучении точных наук вместо развития социальных навыков, пытается взаимодействовать с окружающим миром, семейство Куперов, представляющее собой самую обычную американскую семью, постоянно, но не всегда успешно, пытается найти общий язык со своим не в меру смышлёным дарованием. Это порождает массу комичных ситуаций, в которые попадает не только наш герой, но и всё его окружение.',
        rating: 4.1,
    },
    {
        id: 28,
        nameEn: 'Black Mirror',
        nameRu: 'Черное зеркало',
        imgSm: 'black-mirror-min.jpg',
        imgLg: 'black-mirror-md.jpg',
        video: 'Black Mirror - Season 3 _ Official Trailer [HD] _ Netflix.mp4',
        duration: 43,
        year: 2011,
        type: 'series',
        director: 'Charlie Brooker',
        actors: ['Wunmi Mosaku','Monica Dolan','Daniel Lapaine','Hannah John-Kamen','Michaela Coel'],
        category: ['fantasy','thriller','drama'],
        aboutEn: 'Nowadays, technology has changed our lives and society as a whole. Now every house has a TV, a computer monitor, and even when we leave, we take a phone, smartphone or tablet with us – a black mirror of human existence in the twenty-first century. We trust social networks more than our relatives and friends, we have access to any information, but the truth is that we only have enough for a primitive message. This series shows concern for the current world, and "Black Mirror" reflects everything.',
        aboutRu: 'В наше время технологии изменили нашу жизнь и общество в целом. Сейчас уже в каждом доме есть телевизор, монитор компьютера, и даже уходя, мы берем с собой телефон, смартфон или планшет – черное зеркало существовании человека в двадцать первом веке. Социальным сетям мы доверяем больше чем родным и близким, имеем доступ к любой информации, но правда нас хватает лишь на примитивное сообщение. В этом сериале показано беспокойство за нынешний мир, а «Черное зеркало» все отображает.',
        rating: 4.4,
    },
    {
        id: 29,
        nameEn: 'Trigger',
        nameRu: 'Триггер',
        imgSm: 'trigger-min.jpg',
        imgLg: 'trigger-md.jpg',
        video: 'Триггер трейлер.mp4',
        duration: 52,
        year: 2020,
        type: 'series',
        director: 'Aleksandra Remizova',
        actors: ['Maksim Matveev','Lena Tronina','Svetlana Ivanova','Igor Kostolevskiy','Roman Mayakin'],
        category: ['drama'],
        aboutEn: 'In the center of the story is an experienced psychologist Artyom Streletsky, who adheres to very non-standard methods of treatment. He is convinced that in order to force a person to solve their problems, it is necessary to throw them out of their comfort zone by any means and put them in a non-standard situation. The hero is used to insulting his clients in every possible way and ridiculing their ailments, because this technique has proved to be very effective. However, after many years of successful practice, he will have to face the stumbling block of any specialist, because one of his clients suddenly commits suicide shortly after the session.',
        aboutRu: 'В центре повествования опытный психолог Артем Стрелецкий, который придерживается весьма нестандартных методов лечения. Он убежден, что для того, чтобы заставить человека решить свои проблемы, необходимо любыми методами выкинуть его из зоны комфорта и поставить в нестандартную ситуацию. Герой привык всячески оскорблять своих клиентов и высмеивать их недуги, ведь такая методика показала себя весьма эффективно. Однако, спустя много лет успешной практики, ему предстоит столкнуться с камнем преткновения любого специалиста, ведь один из его клиентов внезапно совершает самоубийство вскоре после сеанса.',
        rating: 4.2,
    },
    {
        id: 30,
        nameEn: 'The Wire',
        nameRu: 'Прослушка',
        imgSm: 'the-wire-min.jpeg',
        imgLg: 'the-wire-md.jpeg',
        video: 'The Wire Season 1 Trailer _ by JPB.mp4',
        duration: 60,
        year: 2002,
        type: 'series',
        director: 'David Simon',
        actors: ['Dominic West','Lance Reddick','Sonja Sohn','Wendell Pierce','John Doman'],
        category: ['drama','thriller','criminal'],
        aboutEn: 'Detective James McNulty is assigned to lead a group that is trying to put local drug lord Avon Barksdale behind bars. Avon, along with his right-hand man Stringer Bell, the mercenary Wee-Bey and numerous subordinates have to deal with cops and informants in their own camp, as well as compete with a competitor Omar, who robs drug dealers and resells drugs. At the same time, Lieutenant Cedric Daniels, who is leading the investigation, is confronted by a corrupt bureaucracy, violent detectives and a hard-headed but determined McNulty.',
        aboutRu: 'Детектив Джеймс Макналти получает задание возглавить группу, которая пытается посадить за решётку местного наркобарона Эйвона Барксдейла. Эйвону вместе с его правой рукой Стрингером Беллом, наёмником Ви-Беем и многочисленными подчинёнными приходится иметь дело копами и информаторами в собственном лагере, а также соперничать с конкурентом Омаром, который грабит наркодилеров и перепродаёт наркотики. В это же время лейтенант Седрик Дэниелс, руководящий расследованием, сталкивается с коррумпированной бюрократией, жестокими детективами и твердолобым, но решительным Макналти.',
        rating: 4.9,
    },
]